In [80]:
import pandas as pd
import numpy as np
from scipy import stats
import re

In [81]:
df = pd.read_csv('cleaned.csv', low_memory=False)
df.head(5)

,Unnamed: 0,Make_Model,Short_Description,Make,Model,Location,Price,Body_Type,Type,Doors,...,Empty_Weight,Full_Service_History,Emission_Class,Upholstery_Colour,Upholstery,Previous_Owner,Com_Conv,Ent_Media,Safe_Secure,Extras2
0,0,Mercedes-Benz A 160,CDi,Mercedes-Benz,A160,ES,16950.0,Compact,Used,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Mercedes-Benz EQE 350,350+,Mercedes-Benz,EQE350,ES,80900.0,Compact,Pre-registered,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Mercedes-Benz A 45 AMG,S 4Matic+ 8G-DCT,Mercedes-Benz,A45AMG,ES,69900.0,Compact,Used,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Mercedes-Benz A 35 AMG,4Matic+ 7G-DCT,Mercedes-Benz,A35AMG,ES,46990.0,Compact,Used,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Mid-Range,Mid-Range,Mid-Range,Luxury
4,4,Mercedes-Benz A 45 AMG,200CDI BE Line 4M 7G-DCT,Mercedes-Benz,A45AMG,ES,16800.0,Compact,Used,5.0,...,1545.0,NaN,NaN,NaN,NaN,NaN,Uncategorized,Mid-Range,Mid-Range,NaN

In [82]:
df0=df.copy()
df1=df.copy()

In [83]:
df.drop(columns='Unnamed: 0',inplace=True)

In [84]:
df.columns

Index(['Make_Model', 'Short_Description', 'Make', 'Model', 'Location', 'Price',
       'Body_Type', 'Type', 'Doors', 'Country_Version', 'Offer_Number',
       'Warranty', 'Mileage', 'First_Registration', 'Gearbox', 'Fuel_Type',
       'Colour', 'Paint', 'Desc', 'Seller', 'Seats', 'Power', 'Engine_Size',
       'Gears', 'Co₂-Emissions', 'Manufacturer_Colour', 'Drivetrain',
       'Cylinders', 'Fuel_Consumption', 'Empty_Weight', 'Full_Service_History',
       'Emission_Class', 'Upholstery_Colour', 'Upholstery', 'Previous_Owner',
       'Com_Conv', 'Ent_Media', 'Safe_Secure', 'Extras2'],
      dtype='object')

In [85]:
df.isnull().sum()

Make_Model                  0
Short_Description         213
Make                        0
Model                     276
Location                    0
Price                       0
Body_Type                   0
Type                        0
Doors                     359
Country_Version         11741
Offer_Number             5530
Warranty                15165
Mileage                     1
First_Registration          2
Gearbox                   248
Fuel_Type                1882
Colour                   1724
Paint                   14135
Desc                      673
Seller                      0
Seats                    3125
Power                     572
Engine_Size              1403
Gears                    9676
Co₂-Emissions           10036
Manufacturer_Colour      6843
Drivetrain              11737
Cylinders                9778
Fuel_Consumption         5245
Empty_Weight            10872
Full_Service_History    16065
Emission_Class          10771
Upholstery_Colour       14061
Upholstery              10020
Previous_Owner          14615
Com_Conv                 3197
Ent_Media                4986
Safe_Secure              3215
Extras2                  5150
dtype: int64

** <b>Columns name: 'Make' and 'Model'<b>

In [86]:
df[['Make_Model', 'Make', 'Model']]

                   Make_Model           Make   Model
0         Mercedes-Benz A 160  Mercedes-Benz    A160
1       Mercedes-Benz EQE 350  Mercedes-Benz  EQE350
2      Mercedes-Benz A 45 AMG  Mercedes-Benz  A45AMG
3      Mercedes-Benz A 35 AMG  Mercedes-Benz  A35AMG
4      Mercedes-Benz A 45 AMG  Mercedes-Benz  A45AMG
...                       ...            ...     ...
28625               Volvo S90          Volvo     S90
28626               Volvo S40          Volvo     S40
28627               Volvo C30          Volvo     C30
28628               Volvo S90          Volvo     S90
28629               Volvo S80          Volvo     S80

[28630 rows x 3 columns]

In [87]:
df['Make'].value_counts(dropna=False)

Volvo            3659
Mercedes-Benz    2398
Opel             2385
Peugeot          2360
Renault          2351
Fiat             2338
Ford             2324
Nissan           2064
Toyota           2038
Hyundai          1867
SEAT             1743
Skoda            1566
Dacia            1537
Name: Make, dtype: int64

In [88]:
df['Model'].value_counts(dropna=False)

Megane      863
Leon        787
V40         740
Sandero     730
i30         706
           ...
GLA35AMG      1
G55AMG        1
Ariya         1
105           1
244           1
Name: Model, Length: 594, dtype: int64

In [89]:
df['Model'].unique()

array(['A160', 'EQE350', 'A45AMG', 'A35AMG', 'C160', 'CLA180', 'A220',
       'A200', 'A250', 'A180', 'GLC220', 'E220', 'B200', 'A150', 'V220',
       'AMGGT', 'E300', 'EQS', 'A140', nan, 'CL', 'B180', 'GLB200',
       'E350', 'CLA200', '280', 'GLA180', 'Viano', 'E53AMG', 'SLK200',
       'GLE350', '220', 'SL500', 'E400', 'SLC43AMG', 'SL350', 'SLC250',
       'SLK350', 'SLS', 'CLK200', 'C400', 'SL65AMG', 'C43AMG', 'C63AMG',
       'SLK250', '500', 'SLK300', 'SLC200', 'SLK55AMG', 'S63AMG', '230',
       'E500', 'SLK', 'SL55AMG', 'CLK55AMG', 'C300', 'SLK280', 'E450',
       'SLC180', 'C200', 'E200', 'SL63AMG', 'SL300', 'S560', 'C180',
       'C250', 'C220', 'E250', 'SL560', 'SLK230', 'SL280', 'SL380',
       'SL600', 'G500', '190', '250', 'CLK350', 'SLC300', 'G320', 'S500',
       'SL320', 'SLR', 'SL400', 'CLK280', 'SL450', 'CLK240', 'CLK230',
       '200', 'CL500', 'CLA220', 'CLA45AMG', 'CLS500', 'S400', 'CL63AMG',
       'CLS350', 'GLC43AMG', 'CLS400', 'CLK63AMG', 'CLS250', '450',
       'CLK500', 'CLA35AMG', 'GLC63AMG', 'CLS320', 'CLK320', 'CLS450',
       '320', 'CLS53AMG', 'CL600', 'GLE43AMG', 'CLA250', 'GLC200',
       'GLE63AMG', 'GLC400', 'CLS', 'GLE400', 'CLK', '350', 'GLC250',
       'S65AMG', 'GLC350', 'CLS300', 'GLE300', 'E50AMG', 'S450', 'GLC300',
       'GLE450', 'ML320', 'ML63AMG', 'ML500', 'GL500', 'GLE580',
       'GLE53AMG', 'G63AMG', 'EQA', 'G400', 'GL63AMG', 'ML450', 'ML300',
       'GLS400', 'ML350', 'EQC400', 'R300', 'GLA45AMG', 'GLK350',
       'GLK220', 'GL350', 'GLB220', 'GLA220', 'GLK250', 'G350', 'GLA250',
       'GLE250', 'ML400', 'EQB350', 'ML250', 'GLA200', 'GLA35AMG',
       'GLK200', 'G', 'G55AMG', 'GLS350', 'GL420', 'GLE500', 'EQB300',
       'GLB250', 'GLB180', 'EQA250', 'G230', 'GLB35AMG', 'X250', 'GL320',
       'GLS63AMG', '170', 'ML280', 'G65AMG', 'Sprinter', 'C350', 'E43AMG',
       'E280', 'CLS63AMG', 'C32AMG', 'E63AMG', 'V300', 'EQE43', 'V250',
       'Vito', 'EQV300', 'B220', 'B250', 'S300', 'C36AMG', 'S580', 'S600',
       'C280', 'S350', 'CLS280', 'S55AMG', 'E240', 'C320', 'E320', 'E230',
       'EQE500', 'S420', '260', 'Corsa', 'Astra', 'Adam', 'Corsa-e',
       'Meriva', 'Karl', 'Agila', 'Insignia', 'Vectra', 'Antara',
       'Ampera', 'GT', 'Cascada', 'Tigra', 'Speedster', 'Kadett',
       'Calibra', 'Manta', 'Commodore', 'Rekord', 'Monza', 'Ascona',
       'CrosslandX', 'Grandland', 'GrandlandX', 'Monterey', 'Mokka',
       'MokkaX', 'Crossland', 'Frontera', 'Mokka-E', 'Vivaro',
       'ZafiraTourer', 'ZafiraLife', 'ComboLife', 'Combo', 'Zafira',
       'Movano', 'Senator', 'Megane', 'Clio', 'Laguna', 'Twingo', 'ZOE',
       'Captur', 'Twizy', 'Fluence', 'GrandScenic', 'R19', 'Avantime',
       'MeganeE-Tech', 'Espace', 'KangooZ.E.', 'AlpineA110', 'Wind',
       'Spider', 'R4', 'Coupe', 'Talisman', 'R9', 'AlpineA310', 'Kangoo',
       'AlpineV6', 'Super5', 'Arkana', 'R5', 'Fuego', 'AlpineA610',
       'Kadjar', 'Alaskan', 'Koleos', 'Scenic', 'Trafic', 'Master',
       'Express', 'GrandEspace', 'P1400', 'Latitude', 'Safrane', 'R18',
       'R21', 'GrandModus', 'R11', '308', '205', '206', '208', '207',
       '1007', '307', '108', 'Rifter', 'e-208', '3008', '508', 'Partner',
       '107', '106', '306', 'iOn', '504', '404', 'Expert', '407', 'RCZ',
       '406', '309', '304', '2008', '4007', '4008', '5008', 'e-2008',
       'Traveller', 'Bipper', 'Ranch', '607', '505', '305', '301',
       'Boxer', '500Abarth', '595Abarth', 'Tipo', 'Stilo', '500X', '500e',
       'Punto', 'Panda', 'Fiorino', 'Seicento', '500C', 'Brava',
       'NewPanda', 'GrandePunto', '850', 'PuntoEvo', '600', 'Bravo',
       '126', 'Uno', '500L', 'Barchetta', '124Spider', 'SpiderEuropa',
       'Dino', '130', '131', 'X1/9', '124Coupè', '128', '127', 'Ritmo',
       'Cinquecento', 'Fullback', 'Freemont', 'Strada', 'Sedici',
       'Talento', 'Croma', 'Qubo', 'Doblo', 'Multipla', 'Leon', 'Ibiza',
       'Toledo', 'Cordoba', 'Arona', 'Mii', 'AlteaXL', 'Arosa', 'Tarraco',
       'Marbella', 'Ateca', 'Altea', 'Alhambra', 'Exeo', 'Leone-Hybrid',
       'Octavia', 'Scala', 'Rapid/Spaceback', 'Fabia', 'Kamiq', 'Citigo',
       'Superb', 'Kodiaq', 'Felicia', '105', 'Karoq', 'Enyaq', 'Yeti',
       'Spring', 'Sandero', 'Logan', 'Lodgy', 'Dokker', 'Duster',
       'Jogger', 'Break', 'Prius', 'AygoX', 'Yaris', 'Aygo', 'Corolla',
       'Auris', 'UrbanCruiser', 'iQ', 'Verso', 'Avensis', 'YarisCross',
       'Starlet', 'Verso-S', 'MR2', 'Supra', 'FJ40', 'Celica',
       'LandCruiser', 'RAV4', 'Paseo', 'C-HR', 'GT86', 'Coaster', 'GR86',
       'Tacoma', 'FJCruiser', 'Hilux', 'Highlander', 'Proace', 'Tundra',
       '4-Runner', 'CorollaVerso', 'Sienna', 'Crown', 'Mirai', 'Camry',
       'Aristo', 'Prius+', 'Leaf', 'Micra', 'Qashqai', 'Juke', 'Pulsar',
       'Note', 'Almera', 'Tiida', 'Primera', 'Titan', '370Z', '280ZX',
       'Datsun', '350Z', '100NX', 'Patrol', 'Figaro', '300ZX', 'GT-R',
       'Skyline', 'Silvia', '200SX', 'Navara', 'Sunny', 'Ariya',
       'X-Trail', 'Murano', 'Terrano', 'Pathfinder', 'Qashqai+2',
       'KingCab', 'Townstar', 'NV300', 'Primastar', 'NV200', 'Stagea',
       'NV250', 'AlmeraTino', 'Evalia', 'Rogue', 'Cube', 'NV400',
       'E-NV200', 'Pixo', 'Gloria', 'Fiesta', 'Focus', 'Mondeo', 'F250',
       'Kuga', 'Ka/Ka+', 'B-Max', 'EcoSport', 'Mustang', 'Bronco', 'Puma',
       'Escort', 'M', 'Thunderbird', 'FocusCC', 'Streetka', 'Fairlane',
       'Galaxy', 'Probe', 'MustangMach-E', 'Cougar', 'Mercury',
       'GranTorino', 'Sierra', 'Capri', 'Explorer', 'Edge', 'Ranger',
       'Maverick', 'F150', 'RangerRaptor', 'TourneoCustom',
       'TransitCustom', 'S-Max', 'TransitConnect', 'TourneoConnect',
       'Transit', 'TourneoCourier', 'GrandTourneo', 'GrandC-Max', 'C-Max',
       'TransitCourier', 'i30', 'i10', 'i20', 'ELANTRA', 'BAYON', 'IONIQ',
       'iX20', 'Getz', 'Terracan', 'KONA', 'ACCENT', 'Excel', 'Atos',
       'VELOSTER', 'TUCSON', 'Genesis', 'GenesisCoupe', 'Tiburon',
       'S-Coupe', 'SANTAFE', 'iX35', 'H-1', 'IONIQ5', 'NEXO',
       'GrandSantaFe', 'i40', 'STARIA', 'Trajet', 'SONATA', 'Lantra',
       'H350', 'KONAElektro', 'Matrix', 'V40', 'S80', 'S60', 'S40',
       'XC60', 'C30', 'V40CrossCountry', 'C70', 'XC90', 'P1800', 'Amazon',
       '480', '240', '262', '780', 'PV544', 'S90', 'C40',
       'V90CrossCountry', 'XC40', 'V60CrossCountry', 'XC70', 'V90', 'V50',
       'V60', 'V70', '740', '945', '440', 'S70', '960', '244'],
      dtype=object)

In [90]:
df.loc[df.Model.isnull()]

,Make_Model,Short_Description,Make,Model,Location,Price,Body_Type,Type,Doors,Country_Version,...,Empty_Weight,Full_Service_History,Emission_Class,Upholstery_Colour,Upholstery,Previous_Owner,Com_Conv,Ent_Media,Safe_Secure,Extras2
162,Mercedes-Benz,Classe A 1.9 116ch A 180 d,Mercedes-Benz,NaN,FR,30490.0,Compact,Used,5.0,France,...,1460.0,NaN,NaN,NaN,NaN,1.0,Mid-Range,Luxury,Luxury,Uncategorized
184,Mercedes-Benz,Classe A 1.5 109ch A 180 CDI BlueEfficiency,Mercedes-Benz,NaN,FR,22790.0,Compact,Used,5.0,France,...,1395.0,NaN,NaN,NaN,NaN,1.0,Mid-Range,Mid-Range,Mid-Range,Uncategorized
186,Mercedes-Benz,Classe A 1.5 116ch A 180 d,Mercedes-Benz,NaN,FR,28790.0,Compact,Used,5.0,France,...,1425.0,NaN,NaN,NaN,NaN,1.0,Mid-Range,Luxury,Luxury,Uncategorized
211,Mercedes-Benz,Classe A 1.5 90ch A 160 CDI / d,Mercedes-Benz,NaN,FR,18390.0,Compact,Used,5.0,France,...,1395.0,NaN,NaN,NaN,NaN,1.0,Mid-Range,Mid-Range,Mid-Range,Uncategorized
213,Mercedes-Benz,Classe A 1.5 116ch A 180 d,Mercedes-Benz,NaN,FR,28290.0,Compact,Used,5.0,France,...,1425.0,NaN,NaN,NaN,full_leather,1.0,Mid-Range,Luxury,Luxury,Uncategorized
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26851,Volvo,1st Edition AWD Recharge Pure Electric Twin,Volvo,NaN,DE,64900.0,Off-Road/Pick-up,Demonstration,5.0,Germany,...,NaN,Yes,NaN,NaN,cloth,1.0,Luxury,Luxury,Luxury,Mid-Range
26893,Volvo,1st Edition AWD Recharge Pure Electric Twin,Volvo,NaN,DE,65400.0,Off-Road/Pick-up,Demonstration,5.0,Germany,...,NaN,Yes,NaN,NaN,cloth,1.0,Luxury,Luxury,Luxury,Mid-Range
27224,Volvo,Ultimate AWD Recharge Pure Electric Twin getön...,Volvo,NaN,DE,68890.0,Off-Road/Pick-up,Demonstration,5.0,Germany,...,2207.0,Yes,NaN,NaN,alcantara,1.0,Luxury,Luxury,Luxury,Uncategorized
27240,Volvo,1st Edition AWD Recharge Pure Electric Twin,Volvo,NaN,DE,64900.0,Off-Road/Pick-up,Demonstration,5.0,Germany,...,NaN,Yes,NaN,NaN,cloth,1.0,Luxury,Luxury,Luxury,Mid-Range
27281,Volvo,1st Edition AWD Recharge Pure Electric Twin,Volvo,NaN,DE,65400.0,Off-Road/Pick-up,Demonstration,5.0,Germany,...,NaN,Yes,NaN,NaN,cloth,1.0,Luxury,Luxury,Luxury,Mid-Range

*First way to filling

In [91]:
df['Model'] = df.apply(lambda x: re.search(r'^(.*?)\s', x['Make_Model']).group(1)\
                      if pd.isnull(x['Model']) else x['Model'], axis=1)

In [92]:
df.iloc[162:164]

,Make_Model,Short_Description,Make,Model,Location,Price,Body_Type,Type,Doors,Country_Version,...,Empty_Weight,Full_Service_History,Emission_Class,Upholstery_Colour,Upholstery,Previous_Owner,Com_Conv,Ent_Media,Safe_Secure,Extras2
162,Mercedes-Benz,Classe A 1.9 116ch A 180 d,Mercedes-Benz,Mercedes-Benz,FR,30490.0,Compact,Used,5.0,France,...,1460.0,NaN,NaN,NaN,NaN,1.0,Mid-Range,Luxury,Luxury,Uncategorized
163,Mercedes-Benz A 180,180d 7G-DCT,Mercedes-Benz,A180,ES,27800.0,Compact,Used,5.0,Spain,...,1425.0,NaN,NaN,NaN,NaN,NaN,Uncategorized,Mid-Range,Mid-Range,Luxury

*Second way to filling by a def function

In [93]:
def extract_make(make_model):
    match = re.search(r'^(.*?)\s', make_model)
    return match.group(1) if match else None

In [94]:
df1['Model'] = df.apply(lambda row: extract_make(row['Make_Model']) if pd.isnull(row['Model']) else row['Model'], axis=1)

In [95]:
df1.iloc[162:164]

,Unnamed: 0,Make_Model,Short_Description,Make,Model,Location,Price,Body_Type,Type,Doors,...,Empty_Weight,Full_Service_History,Emission_Class,Upholstery_Colour,Upholstery,Previous_Owner,Com_Conv,Ent_Media,Safe_Secure,Extras2
162,162,Mercedes-Benz,Classe A 1.9 116ch A 180 d,Mercedes-Benz,Mercedes-Benz,FR,30490.0,Compact,Used,5.0,...,1460.0,NaN,NaN,NaN,NaN,1.0,Mid-Range,Luxury,Luxury,Uncategorized
163,163,Mercedes-Benz A 180,180d 7G-DCT,Mercedes-Benz,A180,ES,27800.0,Compact,Used,5.0,...,1425.0,NaN,NaN,NaN,NaN,NaN,Uncategorized,Mid-Range,Mid-Range,Luxury

In [96]:
df.loc[df.Model.isnull()]

Empty DataFrame
Columns: [Make_Model, Short_Description, Make, Model, Location, Price, Body_Type, Type, Doors, Country_Version, Offer_Number, Warranty, Mileage, First_Registration, Gearbox, Fuel_Type, Colour, Paint, Desc, Seller, Seats, Power, Engine_Size, Gears, Co₂-Emissions, Manufacturer_Colour, Drivetrain, Cylinders, Fuel_Consumption, Empty_Weight, Full_Service_History, Emission_Class, Upholstery_Colour, Upholstery, Previous_Owner, Com_Conv, Ent_Media, Safe_Secure, Extras2]
Index: []

[0 rows x 39 columns]

** <b>Columns name: 'Location' and 'Country_Version'<b>

* I realized that when I clean this column I miss the spaces, so I'll clean them now and than I will start to filling missing values.

In [97]:
df['Country_Version'] = df['Country_Version'].str.replace(" ", "")

In [98]:
df['Location'].value_counts(dropna=False)

DE    12643
ES     6517
NL     2929
IT     2497
BE     1873
FR     1473
AT      660
LU       35
DK        1
EE        1
BG        1
Name: Location, dtype: int64

In [99]:
df['Country_Version'].value_counts(dropna=False)

NaN              11741
Germany           7939
Spain             6376
Italy              679
Belgium            641
EuropeanUnion      340
Netherlands        306
Austria            266
France             101
UnitedStates        57
Czechia             47
Poland              31
Hungary             21
Denmark             21
Romania             12
Japan               12
Switzerland          9
Luxembourg           9
Sweden               6
Slovenia             5
Slovakia             4
Croatia              3
Bulgaria             1
Malta                1
Canada               1
Mexico               1
Name: Country_Version, dtype: int64

In [100]:
df[df.Country_Version.isnull()][['Make','Country_Version', 'Location']]

                Make Country_Version Location
8      Mercedes-Benz             NaN       BE
10     Mercedes-Benz             NaN       BE
13     Mercedes-Benz             NaN       BE
16     Mercedes-Benz             NaN       BE
23     Mercedes-Benz             NaN       BE
...              ...             ...      ...
28620          Volvo             NaN       NL
28623          Volvo             NaN       BE
28626          Volvo             NaN       NL
28628          Volvo             NaN       NL
28629          Volvo             NaN       NL

[11741 rows x 3 columns]

* In below, I tested if 'Country_Version' and 'Location' have any connection.

In [101]:
df[['Country_Version', 'Location']].sample(10)

      Country_Version Location
507               NaN       DE
15951          Poland       DE
21590             NaN       DE
2512          Germany       DE
18274           Spain       ES
13480           Spain       ES
21761         Germany       DE
380             Spain       ES
17122             NaN       NL
2469          Germany       DE

In [102]:
country_mapping = {
    'DE': 'Germany',
    'ES': 'Spain',
    'IT': 'Italy',
    'BE': 'Belgium',
    'FR': 'France',
    'AT': 'Austria',
    'NL': 'Netherland',
    'LU': 'Luxemburg',
    'DK': 'Denmark',
    'EE': 'Europian Union',
    'BG': 'Bulgaria'
}

In [103]:
df['Country_Version'] = df['Country_Version'].fillna(df0['Location'].map(country_mapping))

In [104]:
df['Country_Version'].value_counts(dropna=False)

Germany           12027
Spain              6528
Netherland         2590
Italy              2518
Belgium            1865
France             1436
Austria             744
EuropeanUnion       340
Netherlands         306
UnitedStates         57
Czechia              47
Luxemburg            32
Poland               31
Denmark              22
Hungary              21
Romania              12
Japan                12
Switzerland           9
Luxembourg            9
Sweden                6
Slovenia              5
Slovakia              4
Croatia               3
Bulgaria              2
Europian Union        1
Malta                 1
Canada                1
Mexico                1
Name: Country_Version, dtype: int64

** <b>Columns name: 'Warranty'<b>

In [105]:
df['Warranty']

0        24.0
1        24.0
2        12.0
3        12.0
4        12.0
         ...
28625    12.0
28626     NaN
28627    13.0
28628    12.0
28629     NaN
Name: Warranty, Length: 28630, dtype: float64

In [106]:
df['Warranty'].value_counts(dropna=False)

NaN      15165
12.0      9545
24.0      1515
60.0       968
6.0        398
         ...
55.0         1
99.0         1
122.0        1
44.0         1
4.0          1
Name: Warranty, Length: 65, dtype: int64

In [107]:
df['Warranty'] = df['Warranty'].replace(np.nan, "-")

In [108]:
def exist_warranty(x):
    if '-' in x:
        return 'No'
    else:
        return 'Yes'

In [109]:
df['Warranty'] = df['Warranty'].astype(str).apply(exist_warranty)

In [110]:
df['Warranty'].value_counts(dropna=False)

No     15165
Yes    13465
Name: Warranty, dtype: int64

** <b>Columns name: 'Milage'<b>

In [111]:
df['Mileage']

0        120200.0
1          5000.0
2         18900.0
3         18995.0
4        197000.0
           ...
28625     40345.0
28626    145000.0
28627     96000.0
28628     94343.0
28629    230047.0
Name: Mileage, Length: 28630, dtype: float64

In [112]:
df[df.Mileage.isnull()].T

                                                                  10753
Make_Model                                                    Fiat 500X
Short_Description           1.5 Hybrid Cabrio Automaat Yacht Club Capri
Make                                                               Fiat
Model                                                              500X
Location                                                             NL
Price                                                           41570.0
Body_Type                                             Off-Road/Pick-up
Type                                                     Demonstration
Doors                                                               5.0
Country_Version                                             Netherlands
Offer_Number                                                    #45532
Warranty                                                             No
Mileage                                                             NaN
First_Registration                                           2022-06-01
Gearbox                                                       Automatic
Fuel_Type                                                           NaN
Colour                                                             Blue
Paint                                                          Metallic
Desc                  Modeljaar: 2022Max. Trekgewicht: 1.450 Kg (Ong...
Seller                                                           Dealer
Seats                                                               5.0
Power                                                             131.0
Engine_Size                                                         1.5
Gears                                                               7.0
Co₂-Emissions                                                       NaN
Manufacturer_Colour                                      Blauw metallic
Drivetrain                                                          NaN
Cylinders                                                           4.0
Fuel_Consumption                                                    NaN
Empty_Weight                                                     1380.0
Full_Service_History                                                NaN
Emission_Class                                                      NaN
Upholstery_Colour                                                 Beige
Upholstery                                                 full_leather
Previous_Owner                                                      NaN
Com_Conv                                                      Mid-Range
Ent_Media                                                         Basic
Safe_Secure                                                      Luxury
Extras2                                                       Mid-Range

*There is only one missing value, I got the mean mileage of the same date of first_registration than assigned to the missing value.

In [113]:
mean_of_mielage = df[df.First_Registration=='2022-06-01']['Mileage'].mean().round(0)
mean_of_mielage

2108.0

In [114]:
df[df.Mileage.isnull()]['Mileage']

10753   NaN
Name: Mileage, dtype: float64

In [115]:
df.loc[10753, 'Mileage'] = mean_of_mielage

In [116]:
df.loc[10753, 'Mileage']

2108.0

In [117]:
df['Mileage'].isna().sum()

0

** <b>Columns name: 'Gearbox'<b>

In [118]:
df['Gearbox'].value_counts(dropna=False)

Manual            17023
Automatic         11287
NaN                 248
Semi-automatic       72
Name: Gearbox, dtype: int64

In [119]:
df[(df.Gearbox.isnull())&(df.Make=='Mercedes-Benz')][['Make', 'Model', 'Gearbox']]

               Make          Model Gearbox
150   Mercedes-Benz           A180     NaN
175   Mercedes-Benz         A35AMG     NaN
210   Mercedes-Benz           A200     NaN
222   Mercedes-Benz           A220     NaN
235   Mercedes-Benz           A220     NaN
239   Mercedes-Benz             CL     NaN
241   Mercedes-Benz           A200     NaN
244   Mercedes-Benz           A200     NaN
246   Mercedes-Benz             CL     NaN
247   Mercedes-Benz         A35AMG     NaN
256   Mercedes-Benz           A180     NaN
258   Mercedes-Benz             CL     NaN
259   Mercedes-Benz           A220     NaN
267   Mercedes-Benz           A220     NaN
268   Mercedes-Benz           A180     NaN
931   Mercedes-Benz         CLA250     NaN
1177  Mercedes-Benz           E300     NaN
1396  Mercedes-Benz         GLS400     NaN
2232  Mercedes-Benz  Mercedes-Benz     NaN
2371  Mercedes-Benz  Mercedes-Benz     NaN

In [120]:
df['Gearbox'].sample(10).apply(lambda item: ",".join(item) if type(item) == list else item)

11942       Manual
20033       Manual
11073       Manual
13709       Manual
22234       Manual
12946       Manual
4216        Manual
20645    Automatic
4640     Automatic
27875       Manual
Name: Gearbox, dtype: object

In [121]:
def fill_missing_column_1(df, column):
    mode_column = df.groupby('Model')[column].agg(lambda x: pd.Series.mode(x).values[0])
    model_column_map = mode_column.to_dict()
    
    return model_column_map

In [122]:
model_gearbox_map = fill_missing_column_1(df1,'Gearbox')
model_gearbox_map

{'1007': 'Manual',
 '100NX': 'Manual',
 '105': 'Manual',
 '106': 'Manual',
 '107': 'Manual',
 '108': 'Manual',
 '124Coupè': 'Manual',
 '124Spider': 'Manual',
 '126': 'Manual',
 '127': 'Manual',
 '128': 'Manual',
 '130': 'Automatic',
 '131': 'Manual',
 '170': 'Automatic',
 '190': 'Manual',
 '200': 'Manual',
 '2008': 'Manual',
 '200SX': 'Manual',
 '205': 'Manual',
 '206': 'Manual',
 '207': 'Manual',
 '208': 'Manual',
 '220': 'Manual',
 '230': 'Manual',
 '240': 'Manual',
 '244': 'Automatic',
 '250': 'Automatic',
 '260': 'Automatic',
 '262': 'Automatic',
 '280': 'Manual',
 '280ZX': 'Automatic',
 '3008': 'Automatic',
 '300ZX': 'Manual',
 '301': 'Manual',
 '304': 'Manual',
 '305': 'Automatic',
 '306': 'Manual',
 '307': 'Manual',
 '308': 'Manual',
 '309': 'Manual',
 '320': 'Automatic',
 '350': 'Automatic',
 '350Z': 'Manual',
 '370Z': 'Manual',
 '4-Runner': 'Manual',
 '4007': 'Automatic',
 '4008': 'Manual',
 '404': 'Manual',
 '406': 'Manual',
 '407': 'Manual',
 '440': 'Manual',
 '450': 'Manual',
 '480': 'Manual',
 '500': 'Manual',
 '5008': 'Automatic',
 '500Abarth': 'Manual',
 '500C': 'Manual',
 '500L': 'Manual',
 '500X': 'Manual',
 '500e': 'Automatic',
 '504': 'Manual',
 '505': 'Manual',
 '508': 'Automatic',
 '595Abarth': 'Manual',
 '600': 'Manual',
 '607': 'Automatic',
 '740': 'Manual',
 '780': 'Automatic',
 '850': 'Manual',
 '945': 'Manual',
 '960': 'Automatic',
 'A140': 'Automatic',
 'A150': 'Manual',
 'A160': 'Manual',
 'A180': 'Automatic',
 'A200': 'Automatic',
 'A220': 'Automatic',
 'A250': 'Automatic',
 'A35AMG': 'Automatic',
 'A45AMG': 'Automatic',
 'ACCENT': 'Manual',
 'AMGGT': 'Automatic',
 'Adam': 'Manual',
 'Agila': 'Manual',
 'Alaskan': 'Automatic',
 'Alhambra': 'Automatic',
 'Almera': 'Manual',
 'AlmeraTino': 'Manual',
 'AlpineA110': 'Automatic',
 'AlpineA310': 'Manual',
 'AlpineA610': 'Manual',
 'AlpineV6': 'Manual',
 'Altea': 'Manual',
 'AlteaXL': 'Manual',
 'Amazon': 'Manual',
 'Ampera': 'Automatic',
 'Antara': 'Manual',
 'Aristo': 'Automatic',
 'Ariya': 'Automatic',
 'Arkana': 'Automatic',
 'Arona': 'Manual',
 'Arosa': 'Manual',
 'Ascona': 'Automatic',
 'Astra': 'Manual',
 'Ateca': 'Automatic',
 'Atos': 'Automatic',
 'Auris': 'Automatic',
 'Avantime': 'Manual',
 'Avensis': 'Manual',
 'Aygo': 'Manual',
 'AygoX': 'Manual',
 'B-Max': 'Manual',
 'B180': 'Manual',
 'B200': 'Automatic',
 'B220': 'Automatic',
 'B250': 'Automatic',
 'BAYON': 'Manual',
 'Barchetta': 'Manual',
 'Bipper': 'Manual',
 'Boxer': 'Manual',
 'Brava': 'Manual',
 'Bravo': 'Manual',
 'Break': 'Manual',
 'Bronco': 'Automatic',
 'C-HR': 'Automatic',
 'C-Max': 'Manual',
 'C160': 'Automatic',
 'C180': 'Automatic',
 'C200': 'Automatic',
 'C220': 'Automatic',
 'C250': 'Automatic',
 'C280': 'Automatic',
 'C30': 'Manual',
 'C300': 'Automatic',
 'C320': 'Automatic',
 'C32AMG': 'Manual',
 'C350': 'Automatic',
 'C36AMG': 'Automatic',
 'C40': 'Automatic',
 'C400': 'Automatic',
 'C43AMG': 'Automatic',
 'C63AMG': 'Automatic',
 'C70': 'Automatic',
 'CL': 'Automatic',
 'CL500': 'Automatic',
 'CL600': 'Automatic',
 'CL63AMG': 'Automatic',
 'CLA180': 'Automatic',
 'CLA200': 'Automatic',
 'CLA220': 'Automatic',
 'CLA250': 'Automatic',
 'CLA35AMG': 'Automatic',
 'CLA45AMG': 'Automatic',
 'CLK': 'Automatic',
 'CLK200': 'Automatic',
 'CLK230': 'Automatic',
 'CLK240': 'Automatic',
 'CLK280': 'Automatic',
 'CLK320': 'Automatic',
 'CLK350': 'Automatic',
 'CLK500': 'Automatic',
 'CLK55AMG': 'Automatic',
 'CLK63AMG': 'Automatic',
 'CLS': 'Automatic',
 'CLS250': 'Automatic',
 'CLS280': 'Automatic',
 'CLS300': 'Automatic',
 'CLS320': 'Automatic',
 'CLS350': 'Automatic',
 'CLS400': 'Automatic',
 'CLS450': 'Automatic',
 'CLS500': 'Automatic',
 'CLS53AMG': 'Automatic',
 'CLS63AMG': 'Automatic',
 'Calibra': 'Manual',
 'Camry': 'Automatic',
 'Capri': 'Manual',
 'Captur': 'Manual',
 'Cascada': 'Manual',
 'Celica': 'Manual',
 'Cinquecento': 'Manual',
 'Citigo': 'Manual',
 'Clio': 'Manual',
 'Coaster': 'Automatic',
 'Combo': 'Manual',
 'ComboLife': 'Automatic',
 'Commodore': 'Automatic',
 'Cordoba': 'Manual',
 'Corolla': 'Automatic',
 'CorollaVerso': 'Manual',
 'Corsa': 'Manual',
 'Corsa-e': 'Manual',
 'Cougar': 'Manual',
 'Coupe': 'Manual',
 'Croma': 'Manual',
 'Crossland': 'Manual',
 'CrosslandX': 'Manual',
 'Crown': 'Manual',
 'Cube': 'Manual',
 'Dacia': 'Automatic',
 'Datsun': 'Manual',
 'Dino': 'Manual',
 'Doblo': 'Manual',
 'Dokker': 'Manual',
 'Duster': 'Manual',
 'E-NV200': 'Automatic',
 'E200': 'Automatic',
 'E220': 'Automatic',
 'E230': 'Automatic',
 'E240': 'Automatic',
 'E250': 'Automatic',
 'E280': 'Automatic',
 'E300': 'Automatic',
 'E320': 'Automatic',
 'E350': 'Automatic',
 'E400': 'Automatic',
 'E43AMG': 'Automatic',
 'E450': 'Automatic',
 'E500': 'Automatic',
 'E50AMG': 'Automatic',
 'E53AMG': 'Automatic',
 'E63AMG': 'Automatic',
 'ELANTRA': 'Manual',
 'EQA': 'Automatic',
 'EQA250': 'Automatic',
 'EQB300': 'Automatic',
 'EQB350': 'Automatic',
 'EQC400': 'Automatic',
 'EQE350': 'Automatic',
 'EQE43': 'Automatic',
 'EQE500': 'Automatic',
 'EQS': 'Automatic',
 'EQV300': 'Automatic',
 'EcoSport': 'Manual',
 'Edge': 'Automatic',
 'Enyaq': 'Automatic',
 'Escort': 'Manual',
 'Espace': 'Automatic',
 'Evalia': 'Automatic',
 'Excel': 'Automatic',
 'Exeo': 'Manual',
 'Expert': 'Manual',
 'Explorer': 'Automatic',
 'Express': 'Manual',
 'F150': 'Automatic',
 'F250': 'Automatic',
 'FJ40': 'Manual',
 'FJCruiser': 'Automatic',
 'Fabia': 'Manual',
 'Fairlane': 'Automatic',
 'Felicia': 'Manual',
 'Fiat': 'Manual',
 'Fiesta': 'Manual',
 'Figaro': 'Automatic',
 'Fiorino': 'Manual',
 'Fluence': 'Manual',
 'Focus': 'Manual',
 'FocusCC': 'Manual',
 'Ford': 'Automatic',
 'Freemont': 'Automatic',
 'Frontera': 'Manual',
 'Fuego': 'Manual',
 'Fullback': 'Automatic',
 'G': 'Automatic',
 'G230': 'Automatic',
 'G320': 'Manual',
 'G350': 'Automatic',
 'G400': 'Automatic',
 'G500': 'Automatic',
 'G55AMG': 'Automatic',
 'G63AMG': 'Automatic',
 'G65AMG': 'Automatic',
 'GL320': 'Automatic',
 'GL350': 'Automatic',
 'GL420': 'Automatic',
 'GL500': 'Automatic',
 'GL63AMG': 'Automatic',
 'GLA180': 'Automatic',
 'GLA200': 'Automatic',
 'GLA220': 'Automatic',
 'GLA250': 'Automatic',
 'GLA35AMG': 'Automatic',
 'GLA45AMG': 'Automatic',
 'GLB180': 'Automatic',
 'GLB200': 'Automatic',
 'GLB220': 'Automatic',
 'GLB250': 'Automatic',
 'GLB35AMG': 'Automatic',
 'GLC200': 'Automatic',
 'GLC220': 'Automatic',
 'GLC250': 'Automatic',
 'GLC300': 'Automatic',
 'GLC350': 'Automatic',
 'GLC400': 'Automatic',
 'GLC43AMG': 'Automatic',
 'GLC63AMG': 'Automatic',
 'GLE250': 'Automatic',
 'GLE300': 'Automatic',
 'GLE350': 'Automatic',
 'GLE400': 'Automatic',
 'GLE43AMG': 'Automatic',
 'GLE450': 'Automatic',
 'GLE500': 'Automatic',
 'GLE53AMG': 'Automatic',
 'GLE580': 'Automatic',
 'GLE63AMG': 'Automatic',
 'GLK200': 'Automatic',
 'GLK220': 'Manual',
 'GLK250': 'Automatic',
 'GLK350': 'Automatic',
 'GLS350': 'Automatic',
 'GLS400': 'Automatic',
 'GLS63AMG': 'Automatic',
 'GR86': 'Manual',
 'GT': 'Manual',
 'GT-R': 'Automatic',
 'GT86': 'Manual',
 'Galaxy': 'Automatic',
 'Genesis': 'Manual',
 'GenesisCoupe': 'Manual',
 'Getz': 'Manual',
 'Gloria': 'Automatic',
 'GranTorino': 'Automatic',
 'GrandC-Max': 'Manual',
 'GrandEspace': 'Manual',
 'GrandModus': 'Manual',
 'GrandSantaFe': 'Automatic',
 'GrandScenic': 'Manual',
 'GrandTourneo': 'Manual',
 'GrandePunto': 'Manual',
 'Grandland': 'Automatic',
 'GrandlandX': 'Automatic',
 'H-1': 'Automatic',
 'H350': 'Manual',
 'Highlander': 'Automatic',
 'Hilux': 'Automatic',
 'Hyundai': 'Manual',
 'IONIQ': 'Automatic',
 'IONIQ5': 'Automatic',
 'Ibiza': 'Manual',
 'Insignia': 'Automatic',
 'Jogger': 'Manual',
 'Juke': 'Manual',
 'KONA': 'Automatic',
 'KONAElektro': 'Automatic',
 'Ka/Ka+': 'Manual',
 'Kadett': 'Manual',
 'Kadjar': 'Manual',
 'Kamiq': 'Automatic',
 'Kangoo': 'Manual',
 'KangooZ.E.': 'Manual',
 'Karl': 'Manual',
 'Karoq': 'Automatic',
 'KingCab': 'Manual',
 'Kodiaq': 'Automatic',
 'Koleos': 'Automatic',
 'Kuga': 'Manual',
 'Laguna': 'Manual',
 'LandCruiser': 'Manual',
 'Lantra': 'Manual',
 'Latitude': 'Manual',
 'Leaf': 'Automatic',
 'Leon': 'Manual',
 'Leone-Hybrid': 'Automatic',
 'Lodgy': 'Manual',
 'Logan': 'Manual',
 'M': 'Manual',
 'ML250': 'Automatic',
 'ML280': 'Automatic',
 'ML300': 'Automatic',
 'ML320': 'Automatic',
 'ML350': 'Automatic',
 'ML400': 'Automatic',
 'ML450': 'Automatic',
 'ML500': 'Automatic',
 'ML63AMG': 'Automatic',
 'MR2': 'Manual',
 'Manta': 'Manual',
 'Marbella': 'Manual',
 'Master': 'Manual',
 'Matrix': 'Manual',
 'Maverick': 'Automatic',
 'Megane': 'Manual',
 'MeganeE-Tech': 'Automatic',
 'Mercedes-Benz': 'Automatic',
 'Mercury': 'Automatic',
 'Meriva': 'Manual',
 'Micra': 'Manual',
 'Mii': 'Manual',
 'Mirai': 'Automatic',
 'Mokka': 'Manual',
 'Mokka-E': 'Automatic',
 'MokkaX': 'Manual',
 'Mondeo': 'Automatic',
 'Monterey': 'Manual',
 'Monza': 'Manual',
 'Movano': 'Manual',
 'Multipla': 'Manual',
 'Murano': 'Automatic',
 'Mustang': 'Automatic',
 'MustangMach-E': 'Automatic',
 'NEXO': 'Automatic',
 'NV200': 'Manual',
 'NV250': 'Manual',
 'NV300': 'Manual',
 'NV400': 'Automatic',
 'Navara': 'Manual',
 'NewPanda': 'Manual',
 'Nissan': 'Manual',
 'Note': 'Manual',
 'Octavia': 'Automatic',
 'Opel': 'Manual',
 'P1400': 'Manual',
 'P1800': 'Manual',
 'PV544': 'Manual',
 'Panda': 'Manual',
 'Partner': 'Manual',
 'Paseo': 'Manual',
 'Pathfinder': 'Manual',
 'Patrol': 'Manual',
 'Peugeot': 'Manual',
 'Pixo': 'Manual',
 'Primastar': 'Manual',
 'Primera': 'Manual',
 'Prius': 'Automatic',
 'Prius+': 'Automatic',
 'Proace': 'Manual',
 'Probe': 'Manual',
 'Pulsar': 'Manual',
 'Puma': 'Manual',
 'Punto': 'Manual',
 'PuntoEvo': 'Manual',
 'Qashqai': 'Manual',
 'Qashqai+2': 'Manual',
 'Qubo': 'Manual',
 'R11': 'Automatic',
 'R18': 'Manual',
 'R19': 'Manual',
 'R21': 'Manual',
 'R300': 'Automatic',
 'R4': 'Manual',
 'R5': 'Manual',
 'R9': 'Automatic',
 'RAV4': 'Automatic',
 'RCZ': 'Manual',
 'Ranch': 'Manual',
 'Ranger': 'Automatic',
 'RangerRaptor': 'Automatic',
 'Rapid/Spaceback': 'Manual',
 'Rekord': 'Manual',
 'Renault': 'Automatic',
 'Rifter': 'Manual',
 'Ritmo': 'Manual',
 'Rogue': 'Automatic',
 'S-Coupe': 'Manual',
 'S-Max': 'Automatic',
 'S300': 'Automatic',
 'S350': 'Automatic',
 'S40': 'Manual',
 'S400': 'Automatic',
 'S420': 'Automatic',
 'S450': 'Automatic',
 'S500': 'Automatic',
 'S55AMG': 'Automatic',
 'S560': 'Automatic',
 'S580': 'Automatic',
 'S60': 'Automatic',
 'S600': 'Automatic',
 'S63AMG': 'Automatic',
 'S65AMG': 'Automatic',
 'S70': 'Manual',
 'S80': 'Automatic',
 'S90': 'Automatic',
 'SANTAFE': 'Automatic',
 'SEAT': 'Manual',
 'SL280': 'Automatic',
 'SL300': 'Automatic',
 'SL320': 'Automatic',
 'SL350': 'Automatic',
 'SL380': 'Automatic',
 'SL400': 'Automatic',
 'SL450': 'Automatic',
 'SL500': 'Automatic',
 'SL55AMG': 'Automatic',
 'SL560': 'Automatic',
 'SL600': 'Automatic',
 'SL63AMG': 'Automatic',
 'SL65AMG': 'Automatic',
 'SLC180': 'Manual',
 'SLC200': 'Automatic',
 'SLC250': 'Automatic',
 'SLC300': 'Automatic',
 'SLC43AMG': 'Automatic',
 'SLK': 'Manual',
 'SLK200': 'Manual',
 'SLK230': 'Automatic',
 'SLK250': 'Automatic',
 'SLK280': 'Automatic',
 'SLK300': 'Automatic',
 'SLK350': 'Automatic',
 'SLK55AMG': 'Automatic',
 'SLR': 'Automatic',
 'SLS': 'Automatic',
 'SONATA': 'Manual',
 'STARIA': 'Automatic',
 'Safrane': 'Manual',
 'Sandero': 'Manual',
 'Scala': 'Manual',
 'Scenic': 'Manual',
 'Sedici': 'Manual',
 'Seicento': 'Manual',
 'Senator': 'Automatic',
 'Sienna': 'Automatic',
 'Sierra': 'Manual',
 'Silvia': 'Manual',
 'Skoda': 'Manual',
 'Skyline': 'Manual',
 'Speedster': 'Manual',
 'Spider': 'Manual',
 'SpiderEuropa': 'Manual',
 'Spring': 'Automatic',
 'Sprinter': 'Manual',
 'Stagea': 'Automatic',
 'Starlet': 'Automatic',
 'Stilo': 'Manual',
 'Strada': 'Manual',
 'Streetka': 'Manual',
 'Sunny': 'Manual',
 'Super5': 'Manual',
 'Superb': 'Automatic',
 'Supra': 'Automatic',
 'TUCSON': 'Manual',
 'Tacoma': 'Automatic',
 'Talento': 'Manual',
 'Talisman': 'Automatic',
 'Tarraco': 'Automatic',
 'Terracan': 'Manual',
 'Terrano': 'Manual',
 'Thunderbird': 'Automatic',
 'Tiburon': 'Manual',
 'Tigra': 'Manual',
 'Tiida': 'Manual',
 'Tipo': 'Manual',
 'Titan': 'Automatic',
 'Toledo': 'Manual',
 'TourneoConnect': 'Manual',
 'TourneoCourier': 'Manual',
 'TourneoCustom': 'Manual',
 'Townstar': 'Manual',
 'Toyota': 'Manual',
 'Trafic': 'Manual',
 'Trajet': 'Manual',
 'Transit': 'Manual',
 'TransitConnect': 'Manual',
 'TransitCourier': 'Manual',
 'TransitCustom': 'Manual',
 'Traveller': 'Automatic',
 'Tundra': 'Automatic',
 'Twingo': 'Manual',
 'Twizy': 'Automatic',
 'Uno': 'Manual',
 'UrbanCruiser': 'Manual',
 'V220': 'Automatic',
 'V250': 'Automatic',
 'V300': 'Automatic',
 'V40': 'Manual',
 'V40CrossCountry': 'Automatic',
 'V50': 'Manual',
 'V60': 'Automatic',
 'V60CrossCountry': 'Automatic',
 'V70': 'Automatic',
 'V90': 'Automatic',
 'V90CrossCountry': 'Automatic',
 'VELOSTER': 'Manual',
 'Vectra': 'Manual',
 'Verso': 'Manual',
 'Verso-S': 'Automatic',
 'Viano': 'Automatic',
 'Vito': 'Manual',
 'Vivaro': 'Manual',
 'Volvo': 'Manual',
 'Wind': 'Manual',
 'X-Trail': 'Manual',
 'X1/9': 'Manual',
 'X250': 'Automatic',
 'XC40': 'Automatic',
 'XC60': 'Automatic',
 'XC70': 'Automatic',
 'XC90': 'Automatic',
 'Yaris': 'Automatic',
 'YarisCross': 'Automatic',
 'Yeti': 'Manual',
 'ZOE': 'Automatic',
 'Zafira': 'Automatic',
 'ZafiraLife': 'Automatic',
 'ZafiraTourer': 'Manual',
 'e-2008': 'Automatic',
 'e-208': 'Automatic',
 'i10': 'Manual',
 'i20': 'Manual',
 'i30': 'Manual',
 'i40': 'Manual',
 'iOn': 'Automatic',
 'iQ': 'Automatic',
 'iX20': 'Manual',
 'iX35': 'Manual'}

In [123]:
df[df.Model=='A180']['Gearbox'].mode()

0    Automatic
Name: Gearbox, dtype: object

* In above, I find all mode values of Gearbox for each Model
* In below, I assigned that mode values to each missing values

In [124]:
df['Gearbox'] = df.apply(lambda row: model_gearbox_map[row['Model']] if pd.isnull(row['Gearbox']) else row['Gearbox'], axis=1)

In [125]:
df['Gearbox'].value_counts(dropna=False)

Manual            17190
Automatic         11368
Semi-automatic       72
Name: Gearbox, dtype: int64

** <b>Columns name: 'Fuel_Type'<b>

In [126]:
df['Fuel_Type'].value_counts(dropna=False)

Gasoline    14711
Diesel       8727
Benzine      3122
NaN          1882
Electric      188
Name: Fuel_Type, dtype: int64

In [127]:
fuel_type_mode = df['Fuel_Type'].mode()
fuel_type_mode

0    Gasoline
Name: Fuel_Type, dtype: object

In [128]:
df[df.Fuel_Type.isnull()][['Make', 'Model', 'Fuel_Type']]

                Make Model Fuel_Type
16     Mercedes-Benz  A250       NaN
32     Mercedes-Benz  A250       NaN
93     Mercedes-Benz   EQS       NaN
94     Mercedes-Benz   EQS       NaN
108    Mercedes-Benz   EQS       NaN
...              ...   ...       ...
28565          Volvo   S60       NaN
28566          Volvo   S60       NaN
28591          Volvo   S90       NaN
28618          Volvo   S90       NaN
28625          Volvo   S90       NaN

[1882 rows x 3 columns]

In [129]:
df[['Fuel_Type']]

      Fuel_Type
0        Diesel
1      Electric
2      Gasoline
3      Gasoline
4        Diesel
...         ...
28625       NaN
28626  Gasoline
28627    Diesel
28628  Gasoline
28629  Gasoline

[28630 rows x 1 columns]

In [130]:
model_fuel_dict = df.groupby('Model')['Fuel_Type'].apply(lambda x: pd.Series.mode(x)[0] if len(pd.Series.mode(x)) > 0 else None).to_dict()
model_fuel_dict

{'1007': 'Gasoline',
 '100NX': 'Gasoline',
 '105': 'Diesel',
 '106': 'Gasoline',
 '107': 'Gasoline',
 '108': 'Gasoline',
 '124Coupè': 'Gasoline',
 '124Spider': 'Gasoline',
 '126': 'Gasoline',
 '127': 'Gasoline',
 '128': 'Gasoline',
 '130': 'Gasoline',
 '131': 'Gasoline',
 '170': 'Diesel',
 '190': 'Gasoline',
 '200': 'Benzine',
 '2008': 'Diesel',
 '200SX': 'Gasoline',
 '205': 'Gasoline',
 '206': 'Gasoline',
 '207': 'Gasoline',
 '208': 'Gasoline',
 '220': 'Gasoline',
 '230': 'Gasoline',
 '240': 'Gasoline',
 '244': 'Gasoline',
 '250': 'Gasoline',
 '260': 'Gasoline',
 '262': 'Gasoline',
 '280': 'Gasoline',
 '280ZX': 'Gasoline',
 '3008': 'Diesel',
 '300ZX': 'Gasoline',
 '301': 'Gasoline',
 '304': 'Gasoline',
 '305': 'Gasoline',
 '306': 'Gasoline',
 '307': 'Gasoline',
 '308': 'Diesel',
 '309': 'Gasoline',
 '320': 'Benzine',
 '350': 'Gasoline',
 '350Z': 'Gasoline',
 '370Z': 'Gasoline',
 '4-Runner': 'Gasoline',
 '4007': 'Diesel',
 '4008': 'Diesel',
 '404': 'Gasoline',
 '406': 'Gasoline',
 '407': 'Diesel',
 '440': 'Gasoline',
 '450': 'Gasoline',
 '480': 'Gasoline',
 '500': 'Gasoline',
 '5008': 'Diesel',
 '500Abarth': 'Gasoline',
 '500C': 'Gasoline',
 '500L': 'Diesel',
 '500X': 'Gasoline',
 '500e': 'Electric',
 '504': 'Gasoline',
 '505': 'Gasoline',
 '508': 'Diesel',
 '595Abarth': 'Gasoline',
 '600': 'Gasoline',
 '607': 'Diesel',
 '740': 'Gasoline',
 '780': 'Gasoline',
 '850': 'Gasoline',
 '945': 'Gasoline',
 '960': 'Gasoline',
 'A140': 'Diesel',
 'A150': 'Gasoline',
 'A160': 'Gasoline',
 'A180': 'Diesel',
 'A200': 'Diesel',
 'A220': 'Diesel',
 'A250': 'Gasoline',
 'A35AMG': 'Gasoline',
 'A45AMG': 'Gasoline',
 'ACCENT': 'Gasoline',
 'AMGGT': 'Gasoline',
 'Adam': 'Gasoline',
 'Agila': 'Benzine',
 'Alaskan': 'Diesel',
 'Alhambra': 'Diesel',
 'Almera': 'Diesel',
 'AlmeraTino': 'Gasoline',
 'AlpineA110': 'Gasoline',
 'AlpineA310': 'Gasoline',
 'AlpineA610': 'Gasoline',
 'AlpineV6': 'Gasoline',
 'Altea': 'Diesel',
 'AlteaXL': 'Gasoline',
 'Amazon': 'Gasoline',
 'Ampera': None,
 'Antara': 'Diesel',
 'Aristo': 'Gasoline',
 'Ariya': None,
 'Arkana': 'Gasoline',
 'Arona': 'Gasoline',
 'Arosa': 'Gasoline',
 'Ascona': 'Benzine',
 'Astra': 'Gasoline',
 'Ateca': 'Gasoline',
 'Atos': 'Gasoline',
 'Auris': 'Gasoline',
 'Avantime': 'Gasoline',
 'Avensis': 'Diesel',
 'Aygo': 'Gasoline',
 'AygoX': 'Gasoline',
 'B-Max': 'Gasoline',
 'B180': 'Diesel',
 'B200': 'Diesel',
 'B220': 'Benzine',
 'B250': 'Benzine',
 'BAYON': 'Gasoline',
 'Barchetta': 'Gasoline',
 'Bipper': 'Diesel',
 'Boxer': 'Diesel',
 'Brava': 'Gasoline',
 'Bravo': 'Diesel',
 'Break': 'Gasoline',
 'Bronco': 'Gasoline',
 'C-HR': 'Benzine',
 'C-Max': 'Diesel',
 'C160': 'Gasoline',
 'C180': 'Gasoline',
 'C200': 'Diesel',
 'C220': 'Diesel',
 'C250': 'Diesel',
 'C280': 'Benzine',
 'C30': 'Diesel',
 'C300': 'Benzine',
 'C320': 'Diesel',
 'C32AMG': 'Diesel',
 'C350': 'Gasoline',
 'C36AMG': 'Gasoline',
 'C40': None,
 'C400': 'Gasoline',
 'C43AMG': 'Gasoline',
 'C63AMG': 'Gasoline',
 'C70': 'Gasoline',
 'CL': 'Gasoline',
 'CL500': 'Gasoline',
 'CL600': 'Benzine',
 'CL63AMG': 'Gasoline',
 'CLA180': 'Gasoline',
 'CLA200': 'Diesel',
 'CLA220': 'Diesel',
 'CLA250': 'Benzine',
 'CLA35AMG': 'Gasoline',
 'CLA45AMG': 'Gasoline',
 'CLK': 'Diesel',
 'CLK200': 'Gasoline',
 'CLK230': 'Gasoline',
 'CLK240': 'Gasoline',
 'CLK280': 'Gasoline',
 'CLK320': 'Benzine',
 'CLK350': 'Benzine',
 'CLK500': 'Gasoline',
 'CLK55AMG': 'Benzine',
 'CLK63AMG': 'Gasoline',
 'CLS': 'Diesel',
 'CLS250': 'Diesel',
 'CLS280': 'Gasoline',
 'CLS300': 'Diesel',
 'CLS320': 'Diesel',
 'CLS350': 'Diesel',
 'CLS400': 'Diesel',
 'CLS450': 'Benzine',
 'CLS500': 'Benzine',
 'CLS53AMG': 'Gasoline',
 'CLS63AMG': 'Gasoline',
 'Calibra': 'Gasoline',
 'Camry': 'Gasoline',
 'Capri': 'Gasoline',
 'Captur': 'Gasoline',
 'Cascada': 'Gasoline',
 'Celica': 'Gasoline',
 'Cinquecento': 'Gasoline',
 'Citigo': 'Gasoline',
 'Clio': 'Gasoline',
 'Coaster': 'Gasoline',
 'Combo': 'Diesel',
 'ComboLife': 'Benzine',
 'Commodore': 'Gasoline',
 'Cordoba': 'Diesel',
 'Corolla': 'Gasoline',
 'CorollaVerso': 'Diesel',
 'Corsa': 'Gasoline',
 'Corsa-e': 'Gasoline',
 'Cougar': 'Gasoline',
 'Coupe': 'Gasoline',
 'Croma': 'Diesel',
 'Crossland': 'Gasoline',
 'CrosslandX': 'Gasoline',
 'Crown': 'Gasoline',
 'Cube': 'Gasoline',
 'Dacia': 'Gasoline',
 'Datsun': 'Gasoline',
 'Dino': 'Gasoline',
 'Doblo': 'Diesel',
 'Dokker': 'Diesel',
 'Duster': 'Diesel',
 'E-NV200': None,
 'E200': 'Gasoline',
 'E220': 'Diesel',
 'E230': 'Benzine',
 'E240': 'Gasoline',
 'E250': 'Diesel',
 'E280': 'Benzine',
 'E300': 'Diesel',
 'E320': 'Benzine',
 'E350': 'Diesel',
 'E400': 'Diesel',
 'E43AMG': 'Gasoline',
 'E450': 'Gasoline',
 'E500': 'Gasoline',
 'E50AMG': 'Diesel',
 'E53AMG': 'Benzine',
 'E63AMG': 'Gasoline',
 'ELANTRA': 'Gasoline',
 'EQA': 'Electric',
 'EQA250': None,
 'EQB300': None,
 'EQB350': 'Electric',
 'EQC400': 'Electric',
 'EQE350': 'Electric',
 'EQE43': None,
 'EQE500': None,
 'EQS': 'Electric',
 'EQV300': None,
 'EcoSport': 'Gasoline',
 'Edge': 'Diesel',
 'Enyaq': 'Electric',
 'Escort': 'Gasoline',
 'Espace': 'Gasoline',
 'Evalia': 'Gasoline',
 'Excel': 'Gasoline',
 'Exeo': 'Diesel',
 'Expert': 'Diesel',
 'Explorer': 'Benzine',
 'Express': 'Gasoline',
 'F150': 'Benzine',
 'F250': 'Diesel',
 'FJ40': 'Gasoline',
 'FJCruiser': 'Gasoline',
 'Fabia': 'Gasoline',
 'Fairlane': 'Benzine',
 'Felicia': 'Benzine',
 'Fiat': 'Gasoline',
 'Fiesta': 'Gasoline',
 'Figaro': 'Gasoline',
 'Fiorino': 'Diesel',
 'Fluence': 'Diesel',
 'Focus': 'Gasoline',
 'FocusCC': 'Diesel',
 'Ford': 'Gasoline',
 'Freemont': 'Diesel',
 'Frontera': 'Diesel',
 'Fuego': 'Gasoline',
 'Fullback': 'Diesel',
 'G': 'Diesel',
 'G230': 'Benzine',
 'G320': 'Gasoline',
 'G350': 'Diesel',
 'G400': 'Diesel',
 'G500': 'Gasoline',
 'G55AMG': 'Benzine',
 'G63AMG': 'Gasoline',
 'G65AMG': 'Gasoline',
 'GL320': 'Diesel',
 'GL350': 'Diesel',
 'GL420': 'Diesel',
 'GL500': 'Benzine',
 'GL63AMG': 'Benzine',
 'GLA180': 'Diesel',
 'GLA200': 'Diesel',
 'GLA220': 'Diesel',
 'GLA250': 'Benzine',
 'GLA35AMG': 'Gasoline',
 'GLA45AMG': 'Benzine',
 'GLB180': 'Benzine',
 'GLB200': 'Diesel',
 'GLB220': 'Diesel',
 'GLB250': 'Gasoline',
 'GLB35AMG': 'Benzine',
 'GLC200': 'Gasoline',
 'GLC220': 'Diesel',
 'GLC250': 'Diesel',
 'GLC300': 'Diesel',
 'GLC350': 'Diesel',
 'GLC400': 'Diesel',
 'GLC43AMG': 'Gasoline',
 'GLC63AMG': 'Gasoline',
 'GLE250': 'Diesel',
 'GLE300': 'Diesel',
 'GLE350': 'Diesel',
 'GLE400': 'Diesel',
 'GLE43AMG': 'Gasoline',
 'GLE450': 'Gasoline',
 'GLE500': 'Gasoline',
 'GLE53AMG': 'Gasoline',
 'GLE580': 'Benzine',
 'GLE63AMG': 'Gasoline',
 'GLK200': 'Diesel',
 'GLK220': 'Diesel',
 'GLK250': 'Diesel',
 'GLK350': 'Diesel',
 'GLS350': 'Diesel',
 'GLS400': 'Diesel',
 'GLS63AMG': 'Gasoline',
 'GR86': 'Gasoline',
 'GT': 'Gasoline',
 'GT-R': 'Gasoline',
 'GT86': 'Gasoline',
 'Galaxy': 'Gasoline',
 'Genesis': 'Gasoline',
 'GenesisCoupe': 'Gasoline',
 'Getz': 'Gasoline',
 'Gloria': 'Gasoline',
 'GranTorino': 'Gasoline',
 'GrandC-Max': 'Gasoline',
 'GrandEspace': 'Diesel',
 'GrandModus': 'Gasoline',
 'GrandSantaFe': 'Diesel',
 'GrandScenic': 'Diesel',
 'GrandTourneo': 'Diesel',
 'GrandePunto': 'Gasoline',
 'Grandland': 'Benzine',
 'GrandlandX': 'Gasoline',
 'H-1': 'Diesel',
 'H350': 'Diesel',
 'Highlander': 'Gasoline',
 'Hilux': 'Diesel',
 'Hyundai': 'Gasoline',
 'IONIQ': 'Benzine',
 'IONIQ5': 'Gasoline',
 'Ibiza': 'Gasoline',
 'Insignia': 'Diesel',
 'Jogger': 'Benzine',
 'Juke': 'Gasoline',
 'KONA': 'Gasoline',
 'KONAElektro': None,
 'Ka/Ka+': 'Gasoline',
 'Kadett': 'Gasoline',
 'Kadjar': 'Diesel',
 'Kamiq': 'Gasoline',
 'Kangoo': 'Diesel',
 'KangooZ.E.': 'Diesel',
 'Karl': 'Gasoline',
 'Karoq': 'Diesel',
 'KingCab': 'Diesel',
 'Kodiaq': 'Diesel',
 'Koleos': 'Diesel',
 'Kuga': 'Diesel',
 'Laguna': 'Diesel',
 'LandCruiser': 'Diesel',
 'Lantra': 'Gasoline',
 'Latitude': 'Diesel',
 'Leaf': 'Electric',
 'Leon': 'Gasoline',
 'Leone-Hybrid': 'Benzine',
 'Lodgy': 'Gasoline',
 'Logan': 'Gasoline',
 'M': 'Gasoline',
 'ML250': 'Diesel',
 'ML280': 'Diesel',
 'ML300': 'Diesel',
 'ML320': 'Diesel',
 'ML350': 'Diesel',
 'ML400': 'Diesel',
 'ML450': 'Diesel',
 'ML500': 'Gasoline',
 'ML63AMG': 'Benzine',
 'MR2': 'Gasoline',
 'Manta': 'Gasoline',
 'Marbella': 'Gasoline',
 'Master': 'Diesel',
 'Matrix': 'Gasoline',
 'Maverick': 'Benzine',
 'Megane': 'Gasoline',
 'MeganeE-Tech': 'Diesel',
 'Mercedes-Benz': 'Benzine',
 'Mercury': 'Gasoline',
 'Meriva': 'Gasoline',
 'Micra': 'Gasoline',
 'Mii': 'Gasoline',
 'Mirai': 'Gasoline',
 'Mokka': 'Gasoline',
 'Mokka-E': None,
 'MokkaX': 'Gasoline',
 'Mondeo': 'Diesel',
 'Monterey': 'Diesel',
 'Monza': 'Gasoline',
 'Movano': 'Diesel',
 'Multipla': 'Diesel',
 'Murano': 'Diesel',
 'Mustang': 'Gasoline',
 'MustangMach-E': 'Electric',
 'NEXO': None,
 'NV200': 'Diesel',
 'NV250': 'Gasoline',
 'NV300': 'Diesel',
 'NV400': 'Diesel',
 'Navara': 'Diesel',
 'NewPanda': 'Gasoline',
 'Nissan': 'Gasoline',
 'Note': 'Diesel',
 'Octavia': 'Diesel',
 'Opel': 'Gasoline',
 'P1400': 'Diesel',
 'P1800': 'Gasoline',
 'PV544': 'Gasoline',
 'Panda': 'Gasoline',
 'Partner': 'Diesel',
 'Paseo': 'Gasoline',
 'Pathfinder': 'Diesel',
 'Patrol': 'Diesel',
 'Peugeot': 'Gasoline',
 'Pixo': 'Gasoline',
 'Primastar': 'Diesel',
 'Primera': 'Gasoline',
 'Prius': 'Gasoline',
 'Prius+': None,
 'Proace': 'Diesel',
 'Probe': 'Gasoline',
 'Pulsar': 'Gasoline',
 'Puma': 'Gasoline',
 'Punto': 'Diesel',
 'PuntoEvo': 'Gasoline',
 'Qashqai': 'Diesel',
 'Qashqai+2': 'Diesel',
 'Qubo': 'Gasoline',
 'R11': 'Electric',
 'R18': 'Gasoline',
 'R19': 'Gasoline',
 'R21': 'Gasoline',
 'R300': 'Diesel',
 'R4': 'Gasoline',
 'R5': 'Gasoline',
 'R9': 'Electric',
 'RAV4': 'Gasoline',
 'RCZ': 'Gasoline',
 'Ranch': 'Diesel',
 'Ranger': 'Diesel',
 'RangerRaptor': 'Diesel',
 'Rapid/Spaceback': 'Gasoline',
 'Rekord': 'Gasoline',
 'Renault': 'Gasoline',
 'Rifter': 'Diesel',
 'Ritmo': 'Gasoline',
 'Rogue': 'Gasoline',
 'S-Coupe': 'Gasoline',
 'S-Max': 'Diesel',
 'S300': 'Gasoline',
 'S350': 'Diesel',
 'S40': 'Diesel',
 'S400': 'Diesel',
 'S420': 'Gasoline',
 'S450': 'Benzine',
 'S500': 'Gasoline',
 'S55AMG': 'Benzine',
 'S560': 'Gasoline',
 'S580': 'Benzine',
 'S60': 'Gasoline',
 'S600': 'Benzine',
 'S63AMG': 'Gasoline',
 'S65AMG': 'Gasoline',
 'S70': 'Gasoline',
 'S80': 'Gasoline',
 'S90': 'Diesel',
 'SANTAFE': 'Diesel',
 'SEAT': 'Gasoline',
 'SL280': 'Gasoline',
 'SL300': 'Gasoline',
 'SL320': 'Gasoline',
 'SL350': 'Gasoline',
 'SL380': 'Gasoline',
 'SL400': 'Gasoline',
 'SL450': 'Gasoline',
 'SL500': 'Gasoline',
 'SL55AMG': 'Benzine',
 'SL560': 'Gasoline',
 'SL600': 'Gasoline',
 'SL63AMG': 'Gasoline',
 'SL65AMG': 'Benzine',
 'SLC180': 'Gasoline',
 'SLC200': 'Gasoline',
 'SLC250': 'Diesel',
 'SLC300': 'Gasoline',
 'SLC43AMG': 'Gasoline',
 'SLK': 'Gasoline',
 'SLK200': 'Gasoline',
 'SLK230': 'Gasoline',
 'SLK250': 'Diesel',
 'SLK280': 'Gasoline',
 'SLK300': 'Gasoline',
 'SLK350': 'Gasoline',
 'SLK55AMG': 'Gasoline',
 'SLR': 'Benzine',
 'SLS': 'Benzine',
 'SONATA': 'Gasoline',
 'STARIA': 'Diesel',
 'Safrane': 'Gasoline',
 'Sandero': 'Gasoline',
 'Scala': 'Gasoline',
 'Scenic': 'Diesel',
 'Sedici': 'Gasoline',
 'Seicento': 'Gasoline',
 'Senator': 'Gasoline',
 'Sienna': 'Gasoline',
 'Sierra': 'Gasoline',
 'Silvia': 'Gasoline',
 'Skoda': 'Benzine',
 'Skyline': 'Gasoline',
 'Speedster': 'Gasoline',
 'Spider': 'Gasoline',
 'SpiderEuropa': 'Gasoline',
 'Spring': 'Electric',
 'Sprinter': 'Diesel',
 'Stagea': 'Gasoline',
 'Starlet': 'Gasoline',
 'Stilo': 'Benzine',
 'Strada': 'Diesel',
 'Streetka': 'Gasoline',
 'Sunny': 'Gasoline',
 'Super5': 'Gasoline',
 'Superb': 'Diesel',
 'Supra': 'Gasoline',
 'TUCSON': 'Gasoline',
 'Tacoma': 'Gasoline',
 'Talento': 'Diesel',
 'Talisman': 'Diesel',
 'Tarraco': 'Diesel',
 'Terracan': 'Diesel',
 'Terrano': 'Diesel',
 'Thunderbird': 'Gasoline',
 'Tiburon': 'Gasoline',
 'Tigra': 'Gasoline',
 'Tiida': 'Diesel',
 'Tipo': 'Diesel',
 'Titan': 'Gasoline',
 'Toledo': 'Diesel',
 'TourneoConnect': 'Diesel',
 'TourneoCourier': 'Gasoline',
 'TourneoCustom': 'Diesel',
 'Townstar': 'Gasoline',
 'Toyota': 'Gasoline',
 'Trafic': 'Diesel',
 'Trajet': 'Gasoline',
 'Transit': 'Diesel',
 'TransitConnect': 'Gasoline',
 'TransitCourier': 'Gasoline',
 'TransitCustom': 'Diesel',
 'Traveller': 'Diesel',
 'Tundra': 'Gasoline',
 'Twingo': 'Gasoline',
 'Twizy': 'Electric',
 'Uno': 'Gasoline',
 'UrbanCruiser': 'Gasoline',
 'V220': 'Diesel',
 'V250': 'Diesel',
 'V300': 'Diesel',
 'V40': 'Diesel',
 'V40CrossCountry': 'Gasoline',
 'V50': 'Diesel',
 'V60': 'Diesel',
 'V60CrossCountry': 'Diesel',
 'V70': 'Diesel',
 'V90': 'Diesel',
 'V90CrossCountry': 'Diesel',
 'VELOSTER': 'Gasoline',
 'Vectra': 'Gasoline',
 'Verso': 'Diesel',
 'Verso-S': 'Diesel',
 'Viano': 'Diesel',
 'Vito': 'Diesel',
 'Vivaro': 'Diesel',
 'Volvo': 'Gasoline',
 'Wind': 'Gasoline',
 'X-Trail': 'Diesel',
 'X1/9': 'Gasoline',
 'X250': 'Diesel',
 'XC40': 'Gasoline',
 'XC60': 'Diesel',
 'XC70': 'Diesel',
 'XC90': 'Diesel',
 'Yaris': 'Gasoline',
 'YarisCross': 'Benzine',
 'Yeti': 'Diesel',
 'ZOE': 'Electric',
 'Zafira': 'Benzine',
 'ZafiraLife': 'Diesel',
 'ZafiraTourer': 'Diesel',
 'e-2008': 'Electric',
 'e-208': 'Electric',
 'i10': 'Gasoline',
 'i20': 'Gasoline',
 'i30': 'Gasoline',
 'i40': 'Diesel',
 'iOn': 'Electric',
 'iQ': 'Gasoline',
 'iX20': 'Gasoline',
 'iX35': 'Diesel'}

In [131]:
df['Fuel_Type'] = df['Fuel_Type'].fillna(df['Model'].map(model_fuel_dict))
df['Fuel_Type']

0          Diesel
1        Electric
2        Gasoline
3        Gasoline
4          Diesel
           ...
28625      Diesel
28626    Gasoline
28627      Diesel
28628    Gasoline
28629    Gasoline
Name: Fuel_Type, Length: 28630, dtype: object

In [132]:
df['Fuel_Type'].value_counts(dropna=False)

Gasoline    15680
Diesel       9137
Benzine      3343
Electric      440
None           30
Name: Fuel_Type, dtype: int64

In [133]:
make_fuel_dict = df.groupby('Make')['Fuel_Type'].apply(lambda x: pd.Series.mode(x)[0] if len(pd.Series.mode(x)) > 0 else None).to_dict()
make_fuel_dict

{'Dacia': 'Gasoline',
 'Fiat': 'Gasoline',
 'Ford': 'Gasoline',
 'Hyundai': 'Gasoline',
 'Mercedes-Benz': 'Gasoline',
 'Nissan': 'Gasoline',
 'Opel': 'Gasoline',
 'Peugeot': 'Gasoline',
 'Renault': 'Gasoline',
 'SEAT': 'Gasoline',
 'Skoda': 'Gasoline',
 'Toyota': 'Gasoline',
 'Volvo': 'Diesel'}

In [134]:
df['Fuel_Type'] = df['Fuel_Type'].fillna(df['Make'].map(make_fuel_dict))
df['Fuel_Type']

0          Diesel
1        Electric
2        Gasoline
3        Gasoline
4          Diesel
           ...
28625      Diesel
28626    Gasoline
28627      Diesel
28628    Gasoline
28629    Gasoline
Name: Fuel_Type, Length: 28630, dtype: object

In [135]:
df['Fuel_Type'].value_counts(dropna=False)

Gasoline    15706
Diesel       9141
Benzine      3343
Electric      440
Name: Fuel_Type, dtype: int64

** <b>Columns name: 'Power'<b>

In [136]:
df.Power.value_counts(dropna=False)

150.0     1992
131.0     1356
120.0     1182
110.0     1166
90.0      1110
          ...
1014.0       1
775.0        1
640.0        1
243.0        1
35.0         1
Name: Power, Length: 352, dtype: int64

In [137]:
df.Power.isna().sum()

572

In [138]:
df[df.Power.isnull()][['Make', 'Model', 'Power']]

                Make   Model  Power
0      Mercedes-Benz    A160    NaN
6      Mercedes-Benz  CLA180    NaN
94     Mercedes-Benz     EQS    NaN
100    Mercedes-Benz    A200    NaN
114    Mercedes-Benz    A200    NaN
...              ...     ...    ...
26831          Volvo    XC60    NaN
27220          Volvo    XC60    NaN
27804          Volvo     240    NaN
28184          Volvo     240    NaN
28608          Volvo    XC60    NaN

[572 rows x 3 columns]

In [139]:
df1.Power.astype(object)

0          NaN
1        292.0
2        421.0
3        306.0
4        136.0
         ...
28625    392.0
28626    170.0
28627    114.0
28628    254.0
28629    200.0
Name: Power, Length: 28630, dtype: object

In [140]:
df.groupby('Model')['Power'].apply(lambda x: pd.Series.mode(x)[0] if len(pd.Series.mode(x)) > 0 else None)

Model
1007      73.0
100NX    102.0
105        NaN
106       60.0
107       68.0
         ...
i40      141.0
iOn       67.0
iQ        68.0
iX20      90.0
iX35     135.0
Name: Power, Length: 606, dtype: float64

In [141]:
model_power_dict = df.groupby('Model')['Power'].apply(lambda x: pd.Series.mode(x)[0] if len(pd.Series.mode(x)) > 0 else None).to_dict()
model_power_dict

{'1007': 73.0,
 '100NX': 102.0,
 '105': nan,
 '106': 60.0,
 '107': 68.0,
 '108': 72.0,
 '124Coupè': 118.0,
 '124Spider': 140.0,
 '126': 24.0,
 '127': 54.0,
 '128': 54.0,
 '130': 167.0,
 '131': 65.0,
 '170': 170.0,
 '190': 105.0,
 '200': 163.0,
 '2008': 131.0,
 '200SX': 169.0,
 '205': 102.0,
 '206': 109.0,
 '207': 120.0,
 '208': 82.0,
 '220': 150.0,
 '230': 150.0,
 '240': 102.0,
 '244': 101.0,
 '250': 211.0,
 '260': 160.0,
 '262': 140.0,
 '280': 156.0,
 '280ZX': 200.0,
 '3008': 131.0,
 '300ZX': 283.0,
 '301': nan,
 '304': 75.0,
 '305': 73.0,
 '306': 88.0,
 '307': 136.0,
 '308': 131.0,
 '309': 147.0,
 '320': 218.0,
 '350': 200.0,
 '350Z': 280.0,
 '370Z': 328.0,
 '4-Runner': 143.0,
 '4007': 156.0,
 '4008': 150.0,
 '404': 88.0,
 '406': 207.0,
 '407': 204.0,
 '440': 90.0,
 '450': 224.0,
 '480': 120.0,
 '500': 69.0,
 '5008': 131.0,
 '500Abarth': 179.0,
 '500C': 69.0,
 '500L': 95.0,
 '500X': 120.0,
 '500e': 118.0,
 '504': 10.0,
 '505': 150.0,
 '508': 131.0,
 '595Abarth': 165.0,
 '600': 31.0,
 '607': 133.0,
 '740': 111.0,
 '780': 156.0,
 '850': 48.0,
 '945': 155.0,
 '960': 204.0,
 'A140': 136.0,
 'A150': 95.0,
 'A160': 102.0,
 'A180': 109.0,
 'A200': 136.0,
 'A220': 190.0,
 'A250': 160.0,
 'A35AMG': 306.0,
 'A45AMG': 421.0,
 'ACCENT': 97.0,
 'AMGGT': 557.0,
 'Adam': 87.0,
 'Agila': 58.0,
 'Alaskan': 190.0,
 'Alhambra': 150.0,
 'Almera': 82.0,
 'AlmeraTino': 116.0,
 'AlpineA110': 252.0,
 'AlpineA310': 150.0,
 'AlpineA610': 163.0,
 'AlpineV6': 200.0,
 'Altea': 140.0,
 'AlteaXL': 105.0,
 'Amazon': 92.0,
 'Ampera': nan,
 'Antara': 163.0,
 'Aristo': 280.0,
 'Ariya': 218.0,
 'Arkana': 140.0,
 'Arona': 110.0,
 'Arosa': 60.0,
 'Ascona': 116.0,
 'Astra': 110.0,
 'Ateca': 150.0,
 'Atos': 54.0,
 'Auris': 136.0,
 'Avantime': 150.0,
 'Avensis': 147.0,
 'Aygo': 72.0,
 'AygoX': 72.0,
 'B-Max': 105.0,
 'B180': 109.0,
 'B200': 136.0,
 'B220': 170.0,
 'B250': 224.0,
 'BAYON': 101.0,
 'Barchetta': 131.0,
 'Bipper': 68.0,
 'Boxer': 165.0,
 'Brava': 82.0,
 'Bravo': 105.0,
 'Break': nan,
 'Bronco': 253.0,
 'C-HR': 122.0,
 'C-Max': 95.0,
 'C160': 129.0,
 'C180': 156.0,
 'C200': 184.0,
 'C220': 170.0,
 'C250': 204.0,
 'C280': 231.0,
 'C30': 109.0,
 'C300': 258.0,
 'C320': 224.0,
 'C32AMG': 136.0,
 'C350': 211.0,
 'C36AMG': 280.0,
 'C40': 408.0,
 'C400': 333.0,
 'C43AMG': 390.0,
 'C63AMG': 510.0,
 'C70': 163.0,
 'CL': 118.0,
 'CL500': 387.0,
 'CL600': 367.0,
 'CL63AMG': 525.0,
 'CLA180': 122.0,
 'CLA200': 136.0,
 'CLA220': 170.0,
 'CLA250': 160.0,
 'CLA35AMG': 306.0,
 'CLA45AMG': 421.0,
 'CLK': 150.0,
 'CLK200': 163.0,
 'CLK230': 197.0,
 'CLK240': 170.0,
 'CLK280': 231.0,
 'CLK320': 218.0,
 'CLK350': 272.0,
 'CLK500': 306.0,
 'CLK55AMG': 367.0,
 'CLK63AMG': 481.0,
 'CLS': 204.0,
 'CLS250': 204.0,
 'CLS280': 231.0,
 'CLS300': 265.0,
 'CLS320': 224.0,
 'CLS350': 286.0,
 'CLS400': 340.0,
 'CLS450': 367.0,
 'CLS500': 408.0,
 'CLS53AMG': 435.0,
 'CLS63AMG': 585.0,
 'Calibra': 116.0,
 'Camry': 218.0,
 'Capri': 76.0,
 'Captur': 90.0,
 'Cascada': 170.0,
 'Celica': 143.0,
 'Cinquecento': 19.0,
 'Citigo': 60.0,
 'Clio': 90.0,
 'Coaster': 140.0,
 'Combo': 110.0,
 'ComboLife': 131.0,
 'Commodore': 131.0,
 'Cordoba': 64.0,
 'Corolla': 184.0,
 'CorollaVerso': 129.0,
 'Corsa': 101.0,
 'Corsa-e': 69.0,
 'Cougar': 170.0,
 'Coupe': 220.0,
 'Croma': 150.0,
 'Crossland': 131.0,
 'CrosslandX': 131.0,
 'Crown': 111.0,
 'Cube': 110.0,
 'Dacia': 45.0,
 'Datsun': 88.0,
 'Dino': 163.0,
 'Doblo': 105.0,
 'Dokker': 75.0,
 'Duster': 109.0,
 'E-NV200': 109.0,
 'E200': 184.0,
 'E220': 194.0,
 'E230': 132.0,
 'E240': 177.0,
 'E250': 204.0,
 'E280': 231.0,
 'E300': 245.0,
 'E320': 224.0,
 'E350': 258.0,
 'E400': 340.0,
 'E43AMG': 401.0,
 'E450': 367.0,
 'E500': 306.0,
 'E50AMG': 194.0,
 'E53AMG': 435.0,
 'E63AMG': 612.0,
 'ELANTRA': 132.0,
 'EQA': 190.0,
 'EQA250': 190.0,
 'EQB300': 135.0,
 'EQB350': 292.0,
 'EQC400': 408.0,
 'EQE350': 292.0,
 'EQE43': 476.0,
 'EQE500': 292.0,
 'EQS': 333.0,
 'EQV300': 204.0,
 'EcoSport': 125.0,
 'Edge': 238.0,
 'Enyaq': 204.0,
 'Escort': 105.0,
 'Espace': 224.0,
 'Evalia': 109.0,
 'Excel': 84.0,
 'Exeo': 143.0,
 'Expert': 120.0,
 'Explorer': 457.0,
 'Express': 102.0,
 'F150': 405.0,
 'F250': 330.0,
 'FJ40': 126.0,
 'FJCruiser': 242.0,
 'Fabia': 95.0,
 'Fairlane': 300.0,
 'Felicia': 49.0,
 'Fiat': 48.0,
 'Fiesta': 125.0,
 'Figaro': 64.0,
 'Fiorino': 73.0,
 'Fluence': 110.0,
 'Focus': 125.0,
 'FocusCC': 136.0,
 'Ford': 90.0,
 'Freemont': 170.0,
 'Frontera': 114.0,
 'Fuego': 97.0,
 'Fullback': 181.0,
 'G': 170.0,
 'G230': 116.0,
 'G320': 150.0,
 'G350': 211.0,
 'G400': 330.0,
 'G500': 421.0,
 'G55AMG': 507.0,
 'G63AMG': 585.0,
 'G65AMG': 630.0,
 'GL320': 224.0,
 'GL350': 258.0,
 'GL420': 306.0,
 'GL500': 387.0,
 'GL63AMG': 557.0,
 'GLA180': 122.0,
 'GLA200': 156.0,
 'GLA220': 170.0,
 'GLA250': 211.0,
 'GLA35AMG': 306.0,
 'GLA45AMG': 387.0,
 'GLB180': 136.0,
 'GLB200': 150.0,
 'GLB220': 190.0,
 'GLB250': 224.0,
 'GLB35AMG': 306.0,
 'GLC200': 197.0,
 'GLC220': 170.0,
 'GLC250': 204.0,
 'GLC300': 245.0,
 'GLC350': 258.0,
 'GLC400': 330.0,
 'GLC43AMG': 367.0,
 'GLC63AMG': 476.0,
 'GLE250': 204.0,
 'GLE300': 272.0,
 'GLE350': 258.0,
 'GLE400': 330.0,
 'GLE43AMG': 390.0,
 'GLE450': 367.0,
 'GLE500': 333.0,
 'GLE53AMG': 435.0,
 'GLE580': 489.0,
 'GLE63AMG': 585.0,
 'GLK200': 143.0,
 'GLK220': 170.0,
 'GLK250': 204.0,
 'GLK350': 231.0,
 'GLS350': 258.0,
 'GLS400': 330.0,
 'GLS63AMG': 585.0,
 'GR86': 234.0,
 'GT': 264.0,
 'GT-R': 570.0,
 'GT86': 200.0,
 'Galaxy': 165.0,
 'Genesis': 315.0,
 'GenesisCoupe': 303.0,
 'Getz': 67.0,
 'Gloria': 330.0,
 'GranTorino': nan,
 'GrandC-Max': 125.0,
 'GrandEspace': 110.0,
 'GrandModus': 75.0,
 'GrandSantaFe': 197.0,
 'GrandScenic': 131.0,
 'GrandTourneo': 120.0,
 'GrandePunto': 77.0,
 'Grandland': 131.0,
 'GrandlandX': 131.0,
 'H-1': 170.0,
 'H350': 150.0,
 'Highlander': 247.0,
 'Hilux': 204.0,
 'Hyundai': 101.0,
 'IONIQ': 141.0,
 'IONIQ5': 218.0,
 'Ibiza': 95.0,
 'Insignia': 170.0,
 'Jogger': 110.0,
 'Juke': 110.0,
 'KONA': 120.0,
 'KONAElektro': 53.0,
 'Ka/Ka+': 69.0,
 'Kadett': 60.0,
 'Kadjar': 131.0,
 'Kamiq': 150.0,
 'Kangoo': 90.0,
 'KangooZ.E.': 90.0,
 'Karl': 73.0,
 'Karoq': 150.0,
 'KingCab': 166.0,
 'Kodiaq': 150.0,
 'Koleos': 177.0,
 'Kuga': 150.0,
 'Laguna': 150.0,
 'LandCruiser': 177.0,
 'Lantra': 139.0,
 'Latitude': 150.0,
 'Leaf': 150.0,
 'Leon': 150.0,
 'Leone-Hybrid': 105.0,
 'Lodgy': 116.0,
 'Logan': 90.0,
 'M': 29.0,
 'ML250': 204.0,
 'ML280': 189.0,
 'ML300': 204.0,
 'ML320': 224.0,
 'ML350': 258.0,
 'ML400': 250.0,
 'ML450': 306.0,
 'ML500': 306.0,
 'ML63AMG': 525.0,
 'MR2': 140.0,
 'Manta': 110.0,
 'Marbella': 34.0,
 'Master': 135.0,
 'Matrix': 105.0,
 'Maverick': 250.0,
 'Megane': 110.0,
 'MeganeE-Tech': 91.0,
 'Mercedes-Benz': 381.0,
 'Mercury': 254.0,
 'Meriva': 120.0,
 'Micra': 90.0,
 'Mii': 60.0,
 'Mirai': 154.0,
 'Mokka': 131.0,
 'Mokka-E': 136.0,
 'MokkaX': 140.0,
 'Mondeo': 150.0,
 'Monterey': 114.0,
 'Monza': 140.0,
 'Movano': 163.0,
 'Multipla': 116.0,
 'Murano': 190.0,
 'Mustang': 450.0,
 'MustangMach-E': 269.0,
 'NEXO': 163.0,
 'NV200': 110.0,
 'NV250': 131.0,
 'NV300': 125.0,
 'NV400': 170.0,
 'Navara': 190.0,
 'NewPanda': 69.0,
 'Nissan': 328.0,
 'Note': 90.0,
 'Octavia': 150.0,
 'Opel': 140.0,
 'P1400': 110.0,
 'P1800': 105.0,
 'PV544': 44.0,
 'Panda': 69.0,
 'Partner': 48.0,
 'Paseo': 90.0,
 'Pathfinder': 171.0,
 'Patrol': 95.0,
 'Peugeot': 23.0,
 'Pixo': 68.0,
 'Primastar': 150.0,
 'Primera': 116.0,
 'Prius': 122.0,
 'Prius+': nan,
 'Proace': 131.0,
 'Probe': 162.0,
 'Pulsar': 116.0,
 'Puma': 125.0,
 'Punto': 95.0,
 'PuntoEvo': 101.0,
 'Qashqai': 140.0,
 'Qashqai+2': 150.0,
 'Qubo': 71.0,
 'R11': nan,
 'R18': 126.0,
 'R19': 135.0,
 'R21': 90.0,
 'R300': 190.0,
 'R4': 34.0,
 'R5': 58.0,
 'R9': 90.0,
 'RAV4': 197.0,
 'RCZ': 156.0,
 'Ranch': 90.0,
 'Ranger': 200.0,
 'RangerRaptor': 212.0,
 'Rapid/Spaceback': 90.0,
 'Rekord': 45.0,
 'Renault': 140.0,
 'Rifter': 131.0,
 'Ritmo': 129.0,
 'Rogue': 170.0,
 'S-Coupe': 84.0,
 'S-Max': 190.0,
 'S300': 204.0,
 'S350': 258.0,
 'S40': 136.0,
 'S400': 340.0,
 'S420': 204.0,
 'S450': 367.0,
 'S500': 455.0,
 'S55AMG': 500.0,
 'S560': 469.0,
 'S580': 503.0,
 'S60': 197.0,
 'S600': 517.0,
 'S63AMG': 612.0,
 'S65AMG': 630.0,
 'S70': 140.0,
 'S80': 200.0,
 'S90': 235.0,
 'SANTAFE': 200.0,
 'SEAT': 23.0,
 'SL280': 185.0,
 'SL300': 179.0,
 'SL320': 224.0,
 'SL350': 245.0,
 'SL380': 158.0,
 'SL400': 367.0,
 'SL450': 218.0,
 'SL500': 306.0,
 'SL55AMG': 500.0,
 'SL560': 238.0,
 'SL600': 517.0,
 'SL63AMG': 525.0,
 'SL65AMG': 612.0,
 'SLC180': 156.0,
 'SLC200': 184.0,
 'SLC250': 204.0,
 'SLC300': 245.0,
 'SLC43AMG': 367.0,
 'SLK': 163.0,
 'SLK200': 184.0,
 'SLK230': 193.0,
 'SLK250': 204.0,
 'SLK280': 231.0,
 'SLK300': 231.0,
 'SLK350': 272.0,
 'SLK55AMG': 421.0,
 'SLR': 525.0,
 'SLS': 571.0,
 'SONATA': 162.0,
 'STARIA': 177.0,
 'Safrane': 137.0,
 'Sandero': 90.0,
 'Scala': 150.0,
 'Scenic': 110.0,
 'Sedici': 120.0,
 'Seicento': 39.0,
 'Senator': 204.0,
 'Sienna': 266.0,
 'Sierra': 300.0,
 'Silvia': 250.0,
 'Skoda': 95.0,
 'Skyline': 280.0,
 'Speedster': 147.0,
 'Spider': 147.0,
 'SpiderEuropa': 140.0,
 'Spring': 45.0,
 'Sprinter': 163.0,
 'Stagea': 208.0,
 'Starlet': 73.0,
 'Stilo': 95.0,
 'Strada': 84.0,
 'Streetka': 95.0,
 'Sunny': 75.0,
 'Super5': 173.0,
 'Superb': 150.0,
 'Supra': 340.0,
 'TUCSON': 177.0,
 'Tacoma': 281.0,
 'Talento': 145.0,
 'Talisman': 160.0,
 'Tarraco': 150.0,
 'Terracan': 163.0,
 'Terrano': 125.0,
 'Thunderbird': 179.0,
 'Tiburon': 143.0,
 'Tigra': 90.0,
 'Tiida': 106.0,
 'Tipo': 120.0,
 'Titan': 390.0,
 'Toledo': 116.0,
 'TourneoConnect': 101.0,
 'TourneoCourier': 101.0,
 'TourneoCustom': 105.0,
 'Townstar': 131.0,
 'Toyota': 140.0,
 'Trafic': 120.0,
 'Trajet': 140.0,
 'Transit': 131.0,
 'TransitConnect': 101.0,
 'TransitCourier': 101.0,
 'TransitCustom': 131.0,
 'Traveller': 177.0,
 'Tundra': 386.0,
 'Twingo': 75.0,
 'Twizy': 5.0,
 'Uno': 27.0,
 'UrbanCruiser': 101.0,
 'V220': 163.0,
 'V250': 190.0,
 'V300': 237.0,
 'V40': 120.0,
 'V40CrossCountry': 120.0,
 'V50': 114.0,
 'V60': 190.0,
 'V60CrossCountry': 190.0,
 'V70': 150.0,
 'V90': 190.0,
 'V90CrossCountry': 190.0,
 'VELOSTER': 140.0,
 'Vectra': 155.0,
 'Verso': 132.0,
 'Verso-S': 90.0,
 'Viano': 179.0,
 'Vito': 163.0,
 'Vivaro': 120.0,
 'Volvo': 408.0,
 'Wind': 101.0,
 'X-Trail': 131.0,
 'X1/9': 76.0,
 'X250': 190.0,
 'XC40': 190.0,
 'XC60': 190.0,
 'XC70': 163.0,
 'XC90': 235.0,
 'Yaris': 101.0,
 'YarisCross': 116.0,
 'Yeti': 140.0,
 'ZOE': 109.0,
 'Zafira': 116.0,
 'ZafiraLife': 177.0,
 'ZafiraTourer': 165.0,
 'e-2008': 137.0,
 'e-208': 136.0,
 'i10': 67.0,
 'i20': 101.0,
 'i30': 275.0,
 'i40': 141.0,
 'iOn': 67.0,
 'iQ': 68.0,
 'iX20': 90.0,
 'iX35': 135.0}

In [142]:
df['Power'] = df['Power'].fillna(df['Model'].map(model_power_dict))
df['Power']

0        102.0
1        292.0
2        421.0
3        306.0
4        136.0
         ...
28625    392.0
28626    170.0
28627    114.0
28628    254.0
28629    200.0
Name: Power, Length: 28630, dtype: float64

In [143]:
df['Power'].isna().sum()

7

In [144]:
df[df.Power.isnull()][['Make', 'Model', 'Power']]

          Make       Model  Power
2778      Opel      Ampera    NaN
7103   Renault         R11    NaN
9351   Peugeot         301    NaN
13958    Skoda         105    NaN
16234    Dacia       Break    NaN
18650   Toyota      Prius+    NaN
21752     Ford  GranTorino    NaN

In [145]:
make_power_dict = df.groupby('Make')['Power'].apply(lambda x: pd.Series.mode(x)[0] if len(pd.Series.mode(x)) > 0 else None).to_dict()
make_power_dict

{'Dacia': 90.0,
 'Fiat': 69.0,
 'Ford': 125.0,
 'Hyundai': 120.0,
 'Mercedes-Benz': 170.0,
 'Nissan': 110.0,
 'Opel': 131.0,
 'Peugeot': 131.0,
 'Renault': 90.0,
 'SEAT': 150.0,
 'Skoda': 150.0,
 'Toyota': 136.0,
 'Volvo': 190.0}

In [146]:
df['Power'] = df['Power'].fillna(df['Make'].map(make_power_dict))
df['Power']

0        102.0
1        292.0
2        421.0
3        306.0
4        136.0
         ...
28625    392.0
28626    170.0
28627    114.0
28628    254.0
28629    200.0
Name: Power, Length: 28630, dtype: float64

In [147]:
df['Power'].isna().sum()

0

** <b>Columns name: 'Engine_Size'<b>

In [148]:
df.Engine_Size.value_counts(dropna=False)

2.0      6504
1.6      3795
1.5      3188
1.2      2339
999.0    2068
         ...
20.0        1
498.0       1
839.0       1
698.0       1
3.1         1
Name: Engine_Size, Length: 93, dtype: int64

In [149]:
df['Engine_Size'].isna().sum()

1403

In [150]:
df[df.Engine_Size.isnull()][['Make', 'Model', 'Engine_Size']]

                Make   Model  Engine_Size
0      Mercedes-Benz    A160          NaN
6      Mercedes-Benz  CLA180          NaN
70     Mercedes-Benz    A180          NaN
73     Mercedes-Benz    V220          NaN
93     Mercedes-Benz     EQS          NaN
...              ...     ...          ...
28570          Volvo    XC60          NaN
28586          Volvo     S90          NaN
28606          Volvo    XC60          NaN
28608          Volvo    XC60          NaN
28609          Volvo    XC60          NaN

[1403 rows x 3 columns]

In [151]:
model_engine_dict = df.groupby('Model')['Engine_Size'].apply(lambda x: pd.Series.mode(x)[0] if len(pd.Series.mode(x)) > 0 else None).to_dict()
model_engine_dict

{'1007': 1.4,
 '100NX': 1.6,
 '105': nan,
 '106': 1.1,
 '107': 998.0,
 '108': 998.0,
 '124Coupè': 1.8,
 '124Spider': 1.4,
 '126': 652.0,
 '127': 903.0,
 '128': 1.1,
 '130': 3.2,
 '131': 2.0,
 '170': 2.1,
 '190': nan,
 '200': 1.8,
 '2008': 1.2,
 '200SX': 2.0,
 '205': 1.9,
 '206': 1.6,
 '207': 1.6,
 '208': 1.2,
 '220': 2.2,
 '230': 2.3,
 '240': 2.0,
 '244': 2.1,
 '250': 2.0,
 '260': 2.5,
 '262': 2.7,
 '280': 2.7,
 '280ZX': 0.0,
 '3008': 1.5,
 '300ZX': 3.0,
 '301': nan,
 '304': 1.3,
 '305': 1.5,
 '306': 2.0,
 '307': 2.0,
 '308': 1.6,
 '309': 1.9,
 '320': 3.2,
 '350': 3.5,
 '350Z': 3.5,
 '370Z': 3.7,
 '4-Runner': 3.0,
 '4007': 2.2,
 '4008': 1.8,
 '404': 1.6,
 '406': 2.0,
 '407': 2.7,
 '440': 1.8,
 '450': 4.5,
 '480': 1.7,
 '500': 1.2,
 '5008': 1.5,
 '500Abarth': 1.4,
 '500C': 1.2,
 '500L': 1.4,
 '500X': 1.6,
 '500e': 0.0,
 '504': 2.0,
 '505': 2.2,
 '508': 1.6,
 '595Abarth': 1.4,
 '600': 767.0,
 '607': 2.2,
 '740': 2.0,
 '780': 2.0,
 '850': 843.0,
 '945': 2.0,
 '960': 2.9,
 'A140': nan,
 'A150': 1.5,
 'A160': 1.6,
 'A180': 1.5,
 'A200': 1.3,
 'A220': 2.0,
 'A250': 1.3,
 'A35AMG': 2.0,
 'A45AMG': 2.0,
 'ACCENT': 1.3,
 'AMGGT': 4.0,
 'Adam': 1.4,
 'Agila': 973.0,
 'Alaskan': 2.3,
 'Alhambra': 2.0,
 'Almera': 1.5,
 'AlmeraTino': 1.8,
 'AlpineA110': 1.8,
 'AlpineA310': 2.7,
 'AlpineA610': nan,
 'AlpineV6': 2.5,
 'Altea': 2.0,
 'AlteaXL': 1.4,
 'Amazon': 1.8,
 'Ampera': nan,
 'Antara': 2.2,
 'Aristo': 3.0,
 'Ariya': nan,
 'Arkana': 1.3,
 'Arona': 999.0,
 'Arosa': 1.4,
 'Ascona': nan,
 'Astra': 1.6,
 'Ateca': 2.0,
 'Atos': 1.1,
 'Auris': 1.8,
 'Avantime': 2.0,
 'Avensis': 2.0,
 'Aygo': 998.0,
 'AygoX': 998.0,
 'B-Max': 1.6,
 'B180': 1.5,
 'B200': 2.0,
 'B220': 2.0,
 'B250': 2.0,
 'BAYON': 998.0,
 'Barchetta': 1.7,
 'Bipper': 1.4,
 'Boxer': 2.2,
 'Brava': 1.2,
 'Bravo': 1.6,
 'Break': nan,
 'Bronco': 2.0,
 'C-HR': 2.0,
 'C-Max': 1.5,
 'C160': 1.6,
 'C180': 1.6,
 'C200': 1.5,
 'C220': 2.1,
 'C250': 2.1,
 'C280': 3.0,
 'C30': 1.6,
 'C300': 2.0,
 'C320': 3.0,
 'C32AMG': 2.1,
 'C350': 2.0,
 'C36AMG': 3.6,
 'C40': 0.0,
 'C400': 3.0,
 'C43AMG': 3.0,
 'C63AMG': 4.0,
 'C70': 2.4,
 'CL': 1.3,
 'CL500': 5.5,
 'CL600': 5.5,
 'CL63AMG': 6.2,
 'CLA180': 1.6,
 'CLA200': 1.3,
 'CLA220': 2.1,
 'CLA250': 1.3,
 'CLA35AMG': 2.0,
 'CLA45AMG': 2.0,
 'CLK': 2.1,
 'CLK200': 1.8,
 'CLK230': 2.3,
 'CLK240': 2.6,
 'CLK280': 3.0,
 'CLK320': 3.0,
 'CLK350': 3.5,
 'CLK500': 5.0,
 'CLK55AMG': 5.4,
 'CLK63AMG': 6.2,
 'CLS': 2.1,
 'CLS250': 2.1,
 'CLS280': 3.0,
 'CLS300': 2.0,
 'CLS320': 3.0,
 'CLS350': 3.0,
 'CLS400': 2.9,
 'CLS450': 3.0,
 'CLS500': 4.7,
 'CLS53AMG': 3.0,
 'CLS63AMG': 4.0,
 'Calibra': 2.0,
 'Camry': 2.5,
 'Capri': 1.7,
 'Captur': 1.3,
 'Cascada': 1.6,
 'Celica': 2.0,
 'Cinquecento': nan,
 'Citigo': 999.0,
 'Clio': 1.5,
 'Coaster': 1.8,
 'Combo': 1.5,
 'ComboLife': 1.2,
 'Commodore': 2.5,
 'Cordoba': 1.9,
 'Corolla': 2.0,
 'CorollaVerso': 1.8,
 'Corsa': 1.2,
 'Corsa-e': 1.2,
 'Cougar': 2.5,
 'Coupe': 2.0,
 'Croma': 1.9,
 'Crossland': 1.2,
 'CrosslandX': 1.2,
 'Crown': 2.6,
 'Cube': 1.4,
 'Dacia': 0.0,
 'Datsun': 1.6,
 'Dino': 2.4,
 'Doblo': 1.6,
 'Dokker': 1.5,
 'Duster': 1.5,
 'E-NV200': nan,
 'E200': 2.0,
 'E220': 2.0,
 'E230': 2.3,
 'E240': 2.6,
 'E250': 1.8,
 'E280': 3.0,
 'E300': 2.0,
 'E320': 3.2,
 'E350': 3.0,
 'E400': 2.9,
 'E43AMG': 3.0,
 'E450': 3.0,
 'E500': 4.7,
 'E50AMG': nan,
 'E53AMG': 3.0,
 'E63AMG': 4.0,
 'ELANTRA': 1.6,
 'EQA': nan,
 'EQA250': nan,
 'EQB300': nan,
 'EQB350': nan,
 'EQC400': 1.0,
 'EQE350': 1.0,
 'EQE43': nan,
 'EQE500': nan,
 'EQS': 0.0,
 'EQV300': nan,
 'EcoSport': 998.0,
 'Edge': 2.0,
 'Enyaq': 0.0,
 'Escort': 1.6,
 'Espace': 2.0,
 'Evalia': 1.6,
 'Excel': 1.3,
 'Exeo': 2.0,
 'Expert': 1.5,
 'Explorer': 3.0,
 'Express': 1.3,
 'F150': 3.5,
 'F250': 6.0,
 'FJ40': 3.9,
 'FJCruiser': 4.0,
 'Fabia': 999.0,
 'Fairlane': 5.7,
 'Felicia': 1.1,
 'Fiat': 1.4,
 'Fiesta': 998.0,
 'Figaro': 987.0,
 'Fiorino': 1.2,
 'Fluence': 1.5,
 'Focus': 1.5,
 'FocusCC': 2.0,
 'Ford': 0.0,
 'Freemont': 2.0,
 'Frontera': 2.2,
 'Fuego': 1.6,
 'Fullback': 2.4,
 'G': 2.1,
 'G230': 2.3,
 'G320': 2.7,
 'G350': 3.0,
 'G400': 2.9,
 'G500': 4.0,
 'G55AMG': 5.4,
 'G63AMG': 4.0,
 'G65AMG': 6.0,
 'GL320': 3.0,
 'GL350': 3.0,
 'GL420': 4.0,
 'GL500': 4.7,
 'GL63AMG': 5.5,
 'GLA180': 1.6,
 'GLA200': 1.6,
 'GLA220': 2.1,
 'GLA250': 2.0,
 'GLA35AMG': 2.0,
 'GLA45AMG': 2.0,
 'GLB180': 1.3,
 'GLB200': 1.3,
 'GLB220': 2.0,
 'GLB250': 2.0,
 'GLB35AMG': 2.0,
 'GLC200': 2.0,
 'GLC220': 2.1,
 'GLC250': 2.1,
 'GLC300': 2.0,
 'GLC350': 2.0,
 'GLC400': 2.9,
 'GLC43AMG': 3.0,
 'GLC63AMG': 4.0,
 'GLE250': 2.1,
 'GLE300': 2.0,
 'GLE350': 3.0,
 'GLE400': 2.9,
 'GLE43AMG': 3.0,
 'GLE450': 3.0,
 'GLE500': 3.0,
 'GLE53AMG': 3.0,
 'GLE580': 4.0,
 'GLE63AMG': 4.0,
 'GLK200': 2.1,
 'GLK220': 2.1,
 'GLK250': 2.1,
 'GLK350': 3.0,
 'GLS350': 3.0,
 'GLS400': 2.9,
 'GLS63AMG': 5.5,
 'GR86': 2.4,
 'GT': 2.0,
 'GT-R': 3.8,
 'GT86': 2.0,
 'Galaxy': 1.5,
 'Genesis': 3.8,
 'GenesisCoupe': 2.0,
 'Getz': 1.1,
 'Gloria': 3.0,
 'GranTorino': nan,
 'GrandC-Max': 998.0,
 'GrandEspace': 1.5,
 'GrandModus': 1.1,
 'GrandSantaFe': 2.2,
 'GrandScenic': 1.6,
 'GrandTourneo': 1.5,
 'GrandePunto': 1.4,
 'Grandland': 1.2,
 'GrandlandX': 1.6,
 'H-1': 2.5,
 'H350': 2.5,
 'Highlander': 2.5,
 'Hilux': 2.8,
 'Hyundai': 998.0,
 'IONIQ': 1.6,
 'IONIQ5': 1.0,
 'Ibiza': 999.0,
 'Insignia': 2.0,
 'Jogger': 999.0,
 'Juke': 1.6,
 'KONA': 998.0,
 'KONAElektro': nan,
 'Ka/Ka+': 1.2,
 'Kadett': 1.2,
 'Kadjar': 1.3,
 'Kamiq': 1.5,
 'Kangoo': 1.5,
 'KangooZ.E.': nan,
 'Karl': 999.0,
 'Karoq': 1.5,
 'KingCab': 2.3,
 'Kodiaq': 2.0,
 'Koleos': 2.0,
 'Kuga': 2.0,
 'Laguna': 2.0,
 'LandCruiser': 2.8,
 'Lantra': 2.0,
 'Latitude': 2.0,
 'Leaf': 0.0,
 'Leon': 2.0,
 'Leone-Hybrid': 1.4,
 'Lodgy': 1.5,
 'Logan': 898.0,
 'M': 2.0,
 'ML250': 2.1,
 'ML280': 3.0,
 'ML300': 3.0,
 'ML320': 3.0,
 'ML350': 3.0,
 'ML400': 4.0,
 'ML450': 4.0,
 'ML500': 5.0,
 'ML63AMG': 5.5,
 'MR2': 1.8,
 'Manta': 2.0,
 'Marbella': 843.0,
 'Master': 2.3,
 'Matrix': 1.6,
 'Maverick': 2.0,
 'Megane': 2.0,
 'MeganeE-Tech': 1.6,
 'Mercedes-Benz': 2.0,
 'Mercury': 5.7,
 'Meriva': 1.4,
 'Micra': 999.0,
 'Mii': 999.0,
 'Mirai': 0.0,
 'Mokka': 1.2,
 'Mokka-E': nan,
 'MokkaX': 1.4,
 'Mondeo': 2.0,
 'Monterey': 3.1,
 'Monza': 2.8,
 'Movano': 2.3,
 'Multipla': 1.9,
 'Murano': 2.5,
 'Mustang': 5.0,
 'MustangMach-E': 0.0,
 'NEXO': 0.0,
 'NV200': 1.5,
 'NV250': 1.3,
 'NV300': 2.0,
 'NV400': 2.3,
 'Navara': 2.3,
 'NewPanda': 1.2,
 'Nissan': 3.7,
 'Note': 1.5,
 'Octavia': 2.0,
 'Opel': 1.4,
 'P1400': nan,
 'P1800': 1.8,
 'PV544': 1.6,
 'Panda': 1.2,
 'Partner': 1.6,
 'Paseo': 1.5,
 'Pathfinder': 2.5,
 'Patrol': 2.8,
 'Peugeot': 1.3,
 'Pixo': 996.0,
 'Primastar': 2.0,
 'Primera': 1.8,
 'Prius': 1.8,
 'Prius+': 1.8,
 'Proace': 2.0,
 'Probe': 2.5,
 'Pulsar': 1.2,
 'Puma': 999.0,
 'Punto': 1.2,
 'PuntoEvo': 1.2,
 'Qashqai': 1.3,
 'Qashqai+2': 2.0,
 'Qubo': 1.4,
 'R11': nan,
 'R18': 1.6,
 'R19': 1.8,
 'R21': 1.7,
 'R300': 3.0,
 'R4': 1.1,
 'R5': 1.4,
 'R9': 1.7,
 'RAV4': 2.5,
 'RCZ': 1.6,
 'Ranch': 1.6,
 'Ranger': 3.2,
 'RangerRaptor': 2.0,
 'Rapid/Spaceback': 999.0,
 'Rekord': 1.7,
 'Renault': 1.3,
 'Rifter': 1.5,
 'Ritmo': 2.0,
 'Rogue': 2.5,
 'S-Coupe': 1.5,
 'S-Max': 2.0,
 'S300': 2.1,
 'S350': 2.9,
 'S40': 1.6,
 'S400': 2.9,
 'S420': 4.1,
 'S450': 3.0,
 'S500': 4.7,
 'S55AMG': 5.4,
 'S560': 4.0,
 'S580': 3.0,
 'S60': 2.0,
 'S600': 5.5,
 'S63AMG': 4.0,
 'S65AMG': 6.0,
 'S70': 2.4,
 'S80': 2.4,
 'S90': 2.0,
 'SANTAFE': 2.2,
 'SEAT': 2.0,
 'SL280': 2.7,
 'SL300': 3.0,
 'SL320': 3.2,
 'SL350': 3.5,
 'SL380': 3.8,
 'SL400': 3.0,
 'SL450': nan,
 'SL500': 5.0,
 'SL55AMG': 5.4,
 'SL560': 5.6,
 'SL600': 5.5,
 'SL63AMG': 4.0,
 'SL65AMG': 6.0,
 'SLC180': 1.6,
 'SLC200': 2.0,
 'SLC250': 2.1,
 'SLC300': 2.0,
 'SLC43AMG': 3.0,
 'SLK': 1.8,
 'SLK200': 1.8,
 'SLK230': 2.3,
 'SLK250': 2.1,
 'SLK280': 3.0,
 'SLK300': 3.0,
 'SLK350': 3.5,
 'SLK55AMG': 5.5,
 'SLR': 6.2,
 'SLS': 6.2,
 'SONATA': 2.4,
 'STARIA': 2.2,
 'Safrane': 1.9,
 'Sandero': 999.0,
 'Scala': 999.0,
 'Scenic': 1.5,
 'Sedici': 1.6,
 'Seicento': 899.0,
 'Senator': 3.0,
 'Sienna': 3.5,
 'Sierra': 2.0,
 'Silvia': 2.0,
 'Skoda': 999.0,
 'Skyline': 2.5,
 'Speedster': 2.2,
 'Spider': 2.0,
 'SpiderEuropa': nan,
 'Spring': 0.0,
 'Sprinter': 2.1,
 'Stagea': 2.5,
 'Starlet': 1.3,
 'Stilo': 1.4,
 'Strada': 1.2,
 'Streetka': 1.6,
 'Sunny': 1.6,
 'Super5': 1.4,
 'Superb': 2.0,
 'Supra': 3.0,
 'TUCSON': 1.6,
 'Tacoma': 3.5,
 'Talento': 1.6,
 'Talisman': 1.6,
 'Tarraco': 2.0,
 'Terracan': 2.9,
 'Terrano': 2.7,
 'Thunderbird': 4.0,
 'Tiburon': 2.0,
 'Tigra': 1.4,
 'Tiida': 1.5,
 'Tipo': 1.6,
 'Titan': 5.6,
 'Toledo': 1.6,
 'TourneoConnect': 1.5,
 'TourneoCourier': 998.0,
 'TourneoCustom': 2.0,
 'Townstar': 1.3,
 'Toyota': 1.8,
 'Trafic': 2.0,
 'Trajet': 2.0,
 'Transit': 2.0,
 'TransitConnect': 998.0,
 'TransitCourier': 998.0,
 'TransitCustom': 2.0,
 'Traveller': 2.0,
 'Tundra': 5.7,
 'Twingo': 999.0,
 'Twizy': nan,
 'Uno': 1.1,
 'UrbanCruiser': 1.3,
 'V220': 2.0,
 'V250': 2.0,
 'V300': 2.0,
 'V40': 2.0,
 'V40CrossCountry': 2.0,
 'V50': 1.6,
 'V60': 2.0,
 'V60CrossCountry': 2.0,
 'V70': 2.4,
 'V90': 2.0,
 'V90CrossCountry': 2.0,
 'VELOSTER': 1.6,
 'Vectra': 2.2,
 'Verso': 1.6,
 'Verso-S': 1.3,
 'Viano': nan,
 'Vito': 2.1,
 'Vivaro': 1.6,
 'Volvo': 0.0,
 'Wind': 1.1,
 'X-Trail': 1.6,
 'X1/9': 1.5,
 'X250': 2.3,
 'XC40': 2.0,
 'XC60': 2.0,
 'XC70': 2.4,
 'XC90': 2.0,
 'Yaris': 1.5,
 'YarisCross': 1.5,
 'Yeti': 2.0,
 'ZOE': 0.0,
 'Zafira': 1.6,
 'ZafiraLife': 2.0,
 'ZafiraTourer': 2.0,
 'e-2008': nan,
 'e-208': nan,
 'i10': 998.0,
 'i20': 1.2,
 'i30': 2.0,
 'i40': 1.7,
 'iOn': nan,
 'iQ': 998.0,
 'iX20': 1.4,
 'iX35': 2.0}

In [152]:
df['Engine_Size'] = df['Engine_Size'].fillna(df['Model'].map(model_engine_dict))
df['Engine_Size']

0        1.6
1        1.0
2        2.0
3        2.0
4        2.1
        ...
28625    2.0
28626    2.4
28627    1.6
28628    2.0
28629    2.9
Name: Engine_Size, Length: 28630, dtype: float64

In [153]:
df['Engine_Size'].isna().sum()

80

In [154]:
make_engine_dict = df.groupby('Make')['Engine_Size'].apply(lambda x: pd.Series.mode(x)[0] if len(pd.Series.mode(x)) > 0 else None).to_dict()
make_engine_dict

{'Dacia': 1.5,
 'Fiat': 1.2,
 'Ford': 2.0,
 'Hyundai': 1.6,
 'Mercedes-Benz': 2.0,
 'Nissan': 1.5,
 'Opel': 1.2,
 'Peugeot': 1.6,
 'Renault': 1.5,
 'SEAT': 2.0,
 'Skoda': 2.0,
 'Toyota': 1.8,
 'Volvo': 2.0}

In [155]:
df['Engine_Size'] = df['Engine_Size'].fillna(df['Make'].map(make_engine_dict))
df['Engine_Size']

0        1.6
1        1.0
2        2.0
3        2.0
4        2.1
        ...
28625    2.0
28626    2.4
28627    1.6
28628    2.0
28629    2.9
Name: Engine_Size, Length: 28630, dtype: float64

In [156]:
df['Engine_Size'].isna().sum()

0

** <b>Columns name: 'Com_Conv'<b>

In [157]:
df.Com_Conv.value_counts(dropna=False)

Mid-Range        13991
Luxury            7260
Uncategorized     3997
NaN               3197
Basic              185
Name: Com_Conv, dtype: int64

In [158]:
df['Com_Conv'] = df['Com_Conv'].fillna('Uncategorized')

In [159]:
df.Com_Conv.value_counts(dropna=False)

Mid-Range        13991
Luxury            7260
Uncategorized     7194
Basic              185
Name: Com_Conv, dtype: int64

** <b>Columns name: 'Ent_Media'<b>

In [160]:
df.Ent_Media.value_counts(dropna=False)

Mid-Range        16411
Luxury            5853
NaN               4986
Basic             1308
Uncategorized       72
Name: Ent_Media, dtype: int64

In [161]:
df['Ent_Media'] = df['Ent_Media'].fillna('Uncategorized')

In [162]:
df.Ent_Media.value_counts(dropna=False)

Mid-Range        16411
Luxury            5853
Uncategorized     5058
Basic             1308
Name: Ent_Media, dtype: int64

** <b>Columns name: 'Safe_Secure'<b>

In [163]:
df.Safe_Secure.value_counts(dropna=False)

Mid-Range        15145
Luxury            9454
NaN               3215
Uncategorized      453
Basic              363
Name: Safe_Secure, dtype: int64

In [164]:
df['Safe_Secure'] = df['Safe_Secure'].fillna('Uncategorized')

In [165]:
df.Safe_Secure.value_counts(dropna=False)

Mid-Range        15145
Luxury            9454
Uncategorized     3668
Basic              363
Name: Safe_Secure, dtype: int64

** <b>Columns name: 'Extras2'<b>

In [166]:
df.Extras2.value_counts(dropna=False)

Luxury           12129
Uncategorized     6646
NaN               5150
Mid-Range         3082
Basic             1623
Name: Extras2, dtype: int64

In [167]:
df['Extras2'] = df['Extras2'].fillna('Uncategorized')

In [168]:
df.Extras2.value_counts(dropna=False)

Luxury           12129
Uncategorized    11796
Mid-Range         3082
Basic             1623
Name: Extras2, dtype: int64

** <b>Columns name: 'Gears'<b>

In [169]:
df.Gears.value_counts(dropna=False)

NaN     9676
6.0     8412
5.0     5335
7.0     1738
8.0     1690
1.0      712
9.0      642
4.0      256
10.0     112
0.0       31
3.0       24
2.0        2
Name: Gears, dtype: int64

In [170]:
df[df.Gears.isnull()][['Make', 'Model', 'Gears']]

                Make   Model  Gears
0      Mercedes-Benz    A160    NaN
6      Mercedes-Benz  CLA180    NaN
8      Mercedes-Benz  A35AMG    NaN
15     Mercedes-Benz    A180    NaN
16     Mercedes-Benz    A250    NaN
...              ...     ...    ...
28608          Volvo    XC60    NaN
28609          Volvo    XC60    NaN
28614          Volvo     960    NaN
28615          Volvo     960    NaN
28629          Volvo     S80    NaN

[9676 rows x 3 columns]

In [171]:
model_gears_dict = df.groupby('Model')['Gears'].apply(lambda x: pd.Series.mode(x)[0] if len(pd.Series.mode(x)) > 0 else None).to_dict()
model_gears_dict

{'1007': 5.0,
 '100NX': 5.0,
 '105': nan,
 '106': 5.0,
 '107': 5.0,
 '108': 5.0,
 '124Coupè': 5.0,
 '124Spider': 6.0,
 '126': 4.0,
 '127': 4.0,
 '128': 4.0,
 '130': 5.0,
 '131': 5.0,
 '170': 7.0,
 '190': 4.0,
 '200': nan,
 '2008': 6.0,
 '200SX': 5.0,
 '205': 5.0,
 '206': 5.0,
 '207': 5.0,
 '208': 5.0,
 '220': 4.0,
 '230': nan,
 '240': 1.0,
 '244': nan,
 '250': 7.0,
 '260': nan,
 '262': 3.0,
 '280': 4.0,
 '280ZX': nan,
 '3008': 6.0,
 '300ZX': 5.0,
 '301': nan,
 '304': nan,
 '305': nan,
 '306': 5.0,
 '307': 5.0,
 '308': 6.0,
 '309': 5.0,
 '320': 5.0,
 '350': nan,
 '350Z': 6.0,
 '370Z': 6.0,
 '4-Runner': nan,
 '4007': 6.0,
 '4008': 6.0,
 '404': 4.0,
 '406': 5.0,
 '407': 6.0,
 '440': nan,
 '450': 4.0,
 '480': 5.0,
 '500': 5.0,
 '5008': 6.0,
 '500Abarth': 5.0,
 '500C': 5.0,
 '500L': 6.0,
 '500X': 6.0,
 '500e': 1.0,
 '504': 4.0,
 '505': 5.0,
 '508': 8.0,
 '595Abarth': 5.0,
 '600': 4.0,
 '607': 6.0,
 '740': nan,
 '780': 4.0,
 '850': 4.0,
 '945': 5.0,
 '960': nan,
 'A140': nan,
 'A150': 5.0,
 'A160': 5.0,
 'A180': 7.0,
 'A200': 7.0,
 'A220': 7.0,
 'A250': 7.0,
 'A35AMG': 7.0,
 'A45AMG': 7.0,
 'ACCENT': 5.0,
 'AMGGT': 7.0,
 'Adam': 5.0,
 'Agila': 5.0,
 'Alaskan': 7.0,
 'Alhambra': 6.0,
 'Almera': 5.0,
 'AlmeraTino': 5.0,
 'AlpineA110': 7.0,
 'AlpineA310': 5.0,
 'AlpineA610': 5.0,
 'AlpineV6': 5.0,
 'Altea': 6.0,
 'AlteaXL': 6.0,
 'Amazon': 4.0,
 'Ampera': nan,
 'Antara': 6.0,
 'Aristo': 4.0,
 'Ariya': 1.0,
 'Arkana': 7.0,
 'Arona': 6.0,
 'Arosa': 5.0,
 'Ascona': 1.0,
 'Astra': 6.0,
 'Ateca': 7.0,
 'Atos': nan,
 'Auris': 1.0,
 'Avantime': 6.0,
 'Avensis': 6.0,
 'Aygo': 5.0,
 'AygoX': 5.0,
 'B-Max': 5.0,
 'B180': 6.0,
 'B200': 8.0,
 'B220': 7.0,
 'B250': 7.0,
 'BAYON': 6.0,
 'Barchetta': 5.0,
 'Bipper': 5.0,
 'Boxer': nan,
 'Brava': 5.0,
 'Bravo': 5.0,
 'Break': nan,
 'Bronco': 8.0,
 'C-HR': 1.0,
 'C-Max': 6.0,
 'C160': 9.0,
 'C180': 9.0,
 'C200': 9.0,
 'C220': 9.0,
 'C250': 7.0,
 'C280': nan,
 'C30': 5.0,
 'C300': 9.0,
 'C320': 7.0,
 'C32AMG': 6.0,
 'C350': 7.0,
 'C36AMG': 4.0,
 'C40': 1.0,
 'C400': 9.0,
 'C43AMG': 9.0,
 'C63AMG': 9.0,
 'C70': 5.0,
 'CL': 8.0,
 'CL500': 7.0,
 'CL600': 5.0,
 'CL63AMG': 7.0,
 'CLA180': 7.0,
 'CLA200': 7.0,
 'CLA220': 7.0,
 'CLA250': 7.0,
 'CLA35AMG': 7.0,
 'CLA45AMG': 8.0,
 'CLK': 6.0,
 'CLK200': 6.0,
 'CLK230': nan,
 'CLK240': 6.0,
 'CLK280': 6.0,
 'CLK320': 7.0,
 'CLK350': nan,
 'CLK500': 5.0,
 'CLK55AMG': 5.0,
 'CLK63AMG': 7.0,
 'CLS': 9.0,
 'CLS250': 7.0,
 'CLS280': 7.0,
 'CLS300': 9.0,
 'CLS320': 7.0,
 'CLS350': 9.0,
 'CLS400': 9.0,
 'CLS450': 9.0,
 'CLS500': 7.0,
 'CLS53AMG': 9.0,
 'CLS63AMG': 9.0,
 'Calibra': 5.0,
 'Camry': 1.0,
 'Capri': nan,
 'Captur': 6.0,
 'Cascada': 6.0,
 'Celica': 5.0,
 'Cinquecento': 4.0,
 'Citigo': 5.0,
 'Clio': 5.0,
 'Coaster': 6.0,
 'Combo': 1.0,
 'ComboLife': 8.0,
 'Commodore': 3.0,
 'Cordoba': 5.0,
 'Corolla': 1.0,
 'CorollaVerso': 5.0,
 'Corsa': 5.0,
 'Corsa-e': 5.0,
 'Cougar': 5.0,
 'Coupe': 5.0,
 'Croma': 6.0,
 'Crossland': 6.0,
 'CrosslandX': 6.0,
 'Crown': nan,
 'Cube': 5.0,
 'Dacia': 1.0,
 'Datsun': 4.0,
 'Dino': 5.0,
 'Doblo': 6.0,
 'Dokker': 5.0,
 'Duster': 6.0,
 'E-NV200': 1.0,
 'E200': 9.0,
 'E220': 9.0,
 'E230': nan,
 'E240': 6.0,
 'E250': 7.0,
 'E280': nan,
 'E300': 9.0,
 'E320': nan,
 'E350': 7.0,
 'E400': 9.0,
 'E43AMG': 9.0,
 'E450': 9.0,
 'E500': 5.0,
 'E50AMG': nan,
 'E53AMG': 9.0,
 'E63AMG': 9.0,
 'ELANTRA': 6.0,
 'EQA': 1.0,
 'EQA250': nan,
 'EQB300': nan,
 'EQB350': 1.0,
 'EQC400': 1.0,
 'EQE350': 1.0,
 'EQE43': nan,
 'EQE500': 1.0,
 'EQS': 1.0,
 'EQV300': nan,
 'EcoSport': 6.0,
 'Edge': 8.0,
 'Enyaq': 1.0,
 'Escort': 5.0,
 'Espace': 6.0,
 'Evalia': 5.0,
 'Excel': 0.0,
 'Exeo': 6.0,
 'Expert': 6.0,
 'Explorer': 10.0,
 'Express': 6.0,
 'F150': 10.0,
 'F250': nan,
 'FJ40': 4.0,
 'FJCruiser': nan,
 'Fabia': 5.0,
 'Fairlane': nan,
 'Felicia': 4.0,
 'Fiat': 4.0,
 'Fiesta': 6.0,
 'Figaro': 3.0,
 'Fiorino': nan,
 'Fluence': 6.0,
 'Focus': 6.0,
 'FocusCC': 6.0,
 'Ford': 3.0,
 'Freemont': 6.0,
 'Frontera': 5.0,
 'Fuego': 5.0,
 'Fullback': 6.0,
 'G': 7.0,
 'G230': 4.0,
 'G320': 5.0,
 'G350': 7.0,
 'G400': 9.0,
 'G500': 7.0,
 'G55AMG': nan,
 'G63AMG': 9.0,
 'G65AMG': 7.0,
 'GL320': 7.0,
 'GL350': 7.0,
 'GL420': 7.0,
 'GL500': 7.0,
 'GL63AMG': nan,
 'GLA180': 6.0,
 'GLA200': 6.0,
 'GLA220': 7.0,
 'GLA250': 6.0,
 'GLA35AMG': nan,
 'GLA45AMG': nan,
 'GLB180': nan,
 'GLB200': 8.0,
 'GLB220': 8.0,
 'GLB250': 8.0,
 'GLB35AMG': 8.0,
 'GLC200': 9.0,
 'GLC220': 9.0,
 'GLC250': 9.0,
 'GLC300': 9.0,
 'GLC350': 7.0,
 'GLC400': 9.0,
 'GLC43AMG': 9.0,
 'GLC63AMG': 9.0,
 'GLE250': 9.0,
 'GLE300': 9.0,
 'GLE350': 9.0,
 'GLE400': 9.0,
 'GLE43AMG': 9.0,
 'GLE450': 9.0,
 'GLE500': 7.0,
 'GLE53AMG': 9.0,
 'GLE580': 9.0,
 'GLE63AMG': 7.0,
 'GLK200': 6.0,
 'GLK220': 6.0,
 'GLK250': 7.0,
 'GLK350': 7.0,
 'GLS350': 9.0,
 'GLS400': 9.0,
 'GLS63AMG': 7.0,
 'GR86': 6.0,
 'GT': 5.0,
 'GT-R': 6.0,
 'GT86': 6.0,
 'Galaxy': 6.0,
 'Genesis': 6.0,
 'GenesisCoupe': 6.0,
 'Getz': 5.0,
 'Gloria': nan,
 'GranTorino': nan,
 'GrandC-Max': 6.0,
 'GrandEspace': nan,
 'GrandModus': 5.0,
 'GrandSantaFe': 6.0,
 'GrandScenic': 6.0,
 'GrandTourneo': 6.0,
 'GrandePunto': 5.0,
 'Grandland': 8.0,
 'GrandlandX': 8.0,
 'H-1': 5.0,
 'H350': 6.0,
 'Highlander': 1.0,
 'Hilux': 6.0,
 'Hyundai': 6.0,
 'IONIQ': 6.0,
 'IONIQ5': 1.0,
 'Ibiza': 5.0,
 'Insignia': 6.0,
 'Jogger': 6.0,
 'Juke': 6.0,
 'KONA': 6.0,
 'KONAElektro': nan,
 'Ka/Ka+': 5.0,
 'Kadett': 5.0,
 'Kadjar': 6.0,
 'Kamiq': 7.0,
 'Kangoo': 5.0,
 'KangooZ.E.': nan,
 'Karl': 5.0,
 'Karoq': 7.0,
 'KingCab': nan,
 'Kodiaq': 7.0,
 'Koleos': 6.0,
 'Kuga': 6.0,
 'Laguna': 6.0,
 'LandCruiser': 6.0,
 'Lantra': 5.0,
 'Latitude': nan,
 'Leaf': 1.0,
 'Leon': 6.0,
 'Leone-Hybrid': 6.0,
 'Lodgy': 6.0,
 'Logan': 5.0,
 'M': nan,
 'ML250': 7.0,
 'ML280': 7.0,
 'ML300': nan,
 'ML320': 7.0,
 'ML350': 7.0,
 'ML400': 5.0,
 'ML450': 7.0,
 'ML500': 7.0,
 'ML63AMG': 7.0,
 'MR2': 5.0,
 'Manta': 5.0,
 'Marbella': 4.0,
 'Master': 6.0,
 'Matrix': 5.0,
 'Maverick': 8.0,
 'Megane': 6.0,
 'MeganeE-Tech': 1.0,
 'Mercedes-Benz': 9.0,
 'Mercury': 2.0,
 'Meriva': 6.0,
 'Micra': 5.0,
 'Mii': 5.0,
 'Mirai': 1.0,
 'Mokka': 6.0,
 'Mokka-E': nan,
 'MokkaX': 6.0,
 'Mondeo': 6.0,
 'Monterey': 5.0,
 'Monza': 4.0,
 'Movano': 6.0,
 'Multipla': nan,
 'Murano': 6.0,
 'Mustang': 6.0,
 'MustangMach-E': 1.0,
 'NEXO': nan,
 'NV200': 6.0,
 'NV250': nan,
 'NV300': 6.0,
 'NV400': 6.0,
 'Navara': 6.0,
 'NewPanda': 6.0,
 'Nissan': 5.0,
 'Note': 5.0,
 'Octavia': 6.0,
 'Opel': 6.0,
 'P1400': nan,
 'P1800': 4.0,
 'PV544': 4.0,
 'Panda': 5.0,
 'Partner': 5.0,
 'Paseo': 5.0,
 'Pathfinder': 6.0,
 'Patrol': 5.0,
 'Peugeot': 3.0,
 'Pixo': 5.0,
 'Primastar': 6.0,
 'Primera': 5.0,
 'Prius': 1.0,
 'Prius+': nan,
 'Proace': 6.0,
 'Probe': 5.0,
 'Pulsar': 6.0,
 'Puma': 6.0,
 'Punto': 5.0,
 'PuntoEvo': 5.0,
 'Qashqai': 6.0,
 'Qashqai+2': 6.0,
 'Qubo': 5.0,
 'R11': nan,
 'R18': 5.0,
 'R19': 5.0,
 'R21': 5.0,
 'R300': 7.0,
 'R4': 4.0,
 'R5': 5.0,
 'R9': 3.0,
 'RAV4': 1.0,
 'RCZ': 6.0,
 'Ranch': 5.0,
 'Ranger': 6.0,
 'RangerRaptor': nan,
 'Rapid/Spaceback': 5.0,
 'Rekord': 4.0,
 'Renault': 7.0,
 'Rifter': 6.0,
 'Ritmo': 5.0,
 'Rogue': nan,
 'S-Coupe': 5.0,
 'S-Max': 8.0,
 'S300': 7.0,
 'S350': 9.0,
 'S40': 5.0,
 'S400': 9.0,
 'S420': nan,
 'S450': 7.0,
 'S500': 7.0,
 'S55AMG': nan,
 'S560': 9.0,
 'S580': 9.0,
 'S60': 8.0,
 'S600': 5.0,
 'S63AMG': 7.0,
 'S65AMG': 7.0,
 'S70': 5.0,
 'S80': 6.0,
 'S90': 8.0,
 'SANTAFE': 6.0,
 'SEAT': 4.0,
 'SL280': 4.0,
 'SL300': 1.0,
 'SL320': 5.0,
 'SL350': 7.0,
 'SL380': nan,
 'SL400': 9.0,
 'SL450': nan,
 'SL500': 5.0,
 'SL55AMG': 5.0,
 'SL560': nan,
 'SL600': 5.0,
 'SL63AMG': 7.0,
 'SL65AMG': nan,
 'SLC180': 6.0,
 'SLC200': 6.0,
 'SLC250': 9.0,
 'SLC300': 9.0,
 'SLC43AMG': 9.0,
 'SLK': 6.0,
 'SLK200': 6.0,
 'SLK230': 5.0,
 'SLK250': 7.0,
 'SLK280': 5.0,
 'SLK300': 7.0,
 'SLK350': 7.0,
 'SLK55AMG': 7.0,
 'SLR': nan,
 'SLS': nan,
 'SONATA': 5.0,
 'STARIA': 8.0,
 'Safrane': 5.0,
 'Sandero': 5.0,
 'Scala': 6.0,
 'Scenic': 6.0,
 'Sedici': 5.0,
 'Seicento': 5.0,
 'Senator': 4.0,
 'Sienna': nan,
 'Sierra': 5.0,
 'Silvia': 5.0,
 'Skoda': 5.0,
 'Skyline': 5.0,
 'Speedster': 5.0,
 'Spider': 5.0,
 'SpiderEuropa': nan,
 'Spring': 1.0,
 'Sprinter': 6.0,
 'Stagea': 4.0,
 'Starlet': nan,
 'Stilo': 5.0,
 'Strada': 5.0,
 'Streetka': 5.0,
 'Sunny': 5.0,
 'Super5': 5.0,
 'Superb': 7.0,
 'Supra': 8.0,
 'TUCSON': 6.0,
 'Tacoma': nan,
 'Talento': 6.0,
 'Talisman': 6.0,
 'Tarraco': 7.0,
 'Terracan': 5.0,
 'Terrano': 5.0,
 'Thunderbird': 3.0,
 'Tiburon': 5.0,
 'Tigra': 5.0,
 'Tiida': 6.0,
 'Tipo': 6.0,
 'Titan': nan,
 'Toledo': 5.0,
 'TourneoConnect': 6.0,
 'TourneoCourier': 6.0,
 'TourneoCustom': 6.0,
 'Townstar': 6.0,
 'Toyota': 5.0,
 'Trafic': 6.0,
 'Trajet': 5.0,
 'Transit': 6.0,
 'TransitConnect': 6.0,
 'TransitCourier': nan,
 'TransitCustom': 6.0,
 'Traveller': 6.0,
 'Tundra': nan,
 'Twingo': 5.0,
 'Twizy': 1.0,
 'Uno': 5.0,
 'UrbanCruiser': 5.0,
 'V220': 9.0,
 'V250': 9.0,
 'V300': 9.0,
 'V40': 6.0,
 'V40CrossCountry': 6.0,
 'V50': 6.0,
 'V60': 8.0,
 'V60CrossCountry': 8.0,
 'V70': 5.0,
 'V90': 8.0,
 'V90CrossCountry': 8.0,
 'VELOSTER': 6.0,
 'Vectra': 6.0,
 'Verso': 6.0,
 'Verso-S': 6.0,
 'Viano': nan,
 'Vito': nan,
 'Vivaro': 6.0,
 'Volvo': 4.0,
 'Wind': 5.0,
 'X-Trail': 6.0,
 'X1/9': 5.0,
 'X250': 7.0,
 'XC40': 8.0,
 'XC60': 8.0,
 'XC70': 6.0,
 'XC90': 8.0,
 'Yaris': 6.0,
 'YarisCross': 1.0,
 'Yeti': 6.0,
 'ZOE': 1.0,
 'Zafira': 5.0,
 'ZafiraLife': 6.0,
 'ZafiraTourer': nan,
 'e-2008': 1.0,
 'e-208': 1.0,
 'i10': 5.0,
 'i20': 5.0,
 'i30': 6.0,
 'i40': 6.0,
 'iOn': nan,
 'iQ': 5.0,
 'iX20': 6.0,
 'iX35': 6.0}

In [172]:
df['Gears'] = df['Gears'].fillna(df['Model'].map(model_gears_dict))
df['Gears']

0        5.0
1        9.0
2        8.0
3        7.0
4        7.0
        ...
28625    8.0
28626    5.0
28627    6.0
28628    8.0
28629    6.0
Name: Gears, Length: 28630, dtype: float64

In [173]:
df['Gears'].isna().sum()

130

In [174]:
make_gears_dict = df.groupby('Make')['Gears'].apply(lambda x: pd.Series.mode(x)[0] if len(pd.Series.mode(x)) > 0 else None).to_dict()
make_gears_dict

{'Dacia': 5.0,
 'Fiat': 5.0,
 'Ford': 6.0,
 'Hyundai': 6.0,
 'Mercedes-Benz': 9.0,
 'Nissan': 6.0,
 'Opel': 6.0,
 'Peugeot': 6.0,
 'Renault': 6.0,
 'SEAT': 6.0,
 'Skoda': 7.0,
 'Toyota': 1.0,
 'Volvo': 8.0}

In [175]:
df['Gears'] = df['Gears'].fillna(df['Make'].map(make_gears_dict))
df['Gears']

0        5.0
1        9.0
2        8.0
3        7.0
4        7.0
        ...
28625    8.0
28626    5.0
28627    6.0
28628    8.0
28629    6.0
Name: Gears, Length: 28630, dtype: float64

In [176]:
df0['Gears'].isna().sum()

9676

In [177]:
df.columns

Index(['Make_Model', 'Short_Description', 'Make', 'Model', 'Location', 'Price',
       'Body_Type', 'Type', 'Doors', 'Country_Version', 'Offer_Number',
       'Warranty', 'Mileage', 'First_Registration', 'Gearbox', 'Fuel_Type',
       'Colour', 'Paint', 'Desc', 'Seller', 'Seats', 'Power', 'Engine_Size',
       'Gears', 'Co₂-Emissions', 'Manufacturer_Colour', 'Drivetrain',
       'Cylinders', 'Fuel_Consumption', 'Empty_Weight', 'Full_Service_History',
       'Emission_Class', 'Upholstery_Colour', 'Upholstery', 'Previous_Owner',
       'Com_Conv', 'Ent_Media', 'Safe_Secure', 'Extras2'],
      dtype='object')

In [178]:
df.isnull().sum()

Make_Model                  0
Short_Description         213
Make                        0
Model                       0
Location                    0
Price                       0
Body_Type                   0
Type                        0
Doors                     359
Country_Version             0
Offer_Number             5530
Warranty                    0
Mileage                     0
First_Registration          2
Gearbox                     0
Fuel_Type                   0
Colour                   1724
Paint                   14135
Desc                      673
Seller                      0
Seats                    3125
Power                       0
Engine_Size                 0
Gears                       0
Co₂-Emissions           10036
Manufacturer_Colour      6843
Drivetrain              11737
Cylinders                9778
Fuel_Consumption         5245
Empty_Weight            10872
Full_Service_History    16065
Emission_Class          10771
Upholstery_Colour       14061
Upholstery              10020
Previous_Owner          14615
Com_Conv                    0
Ent_Media                   0
Safe_Secure                 0
Extras2                     0
dtype: int64

In [179]:
df.drop(columns=['Paint', 'Drivetrain','Empty_Weight', 'Full_Service_History', 'Upholstery_Colour','Previous_Owner','Co₂-Emissions'], inplace=True)

In [180]:
df.to_csv("filled_missing_values.csv")